(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 2024,
	height: 1334,
	fps: 20,
	color: "#CDCDCD",
	manifest: [
		{src:"images/Background.png", id:"Background"},
		{src:"images/Dave_1.png", id:"Dave_1"},
		{src:"images/Dave_2.png", id:"Dave_2"},
		{src:"images/Dave_3.png", id:"Dave_3"},
		{src:"images/DaveBitmapped.png", id:"DaveBitmapped"},
		{src:"images/Desk.png", id:"Desk"},
		{src:"images/Jose_1.png", id:"Jose_1"},
		{src:"images/Jose_2.png", id:"Jose_2"},
		{src:"images/Jose_3.png", id:"Jose_3"},
		{src:"images/JoseBitmapped.png", id:"JoseBitmapped"},
		{src:"images/Pat_1.png", id:"Pat_1"},
		{src:"images/Pat_2.png", id:"Pat_2"},
		{src:"images/Pat_3.png", id:"Pat_3"},
		{src:"images/PatBitmapped.png", id:"PatBitmapped"},
		{src:"images/Register.png", id:"Register"}
	]
};



// symbols:



(lib.Background = function() {
	this.initialize(img.Background);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2024,1334);


(lib.Dave_1 = function() {
	this.initialize(img.Dave_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,742,196);


(lib.Dave_2 = function() {
	this.initialize(img.Dave_2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,839,259);


(lib.Dave_3 = function() {
	this.initialize(img.Dave_3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,790,196);


(lib.DaveBitmapped = function() {
	this.initialize(img.DaveBitmapped);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,123,205);


(lib.Desk = function() {
	this.initialize(img.Desk);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2027,567);


(lib.Jose_1 = function() {
	this.initialize(img.Jose_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,836,196);


(lib.Jose_2 = function() {
	this.initialize(img.Jose_2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,797,196);


(lib.Jose_3 = function() {
	this.initialize(img.Jose_3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,855,287);


(lib.JoseBitmapped = function() {
	this.initialize(img.JoseBitmapped);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,165,212);


(lib.Pat_1 = function() {
	this.initialize(img.Pat_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,687,196);


(lib.Pat_2 = function() {
	this.initialize(img.Pat_2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,714,196);


(lib.Pat_3 = function() {
	this.initialize(img.Pat_3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,714,196);


(lib.PatBitmapped = function() {
	this.initialize(img.PatBitmapped);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,137,211);


(lib.Register = function() {
	this.initialize(img.Register);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1061,566);


(lib.cover = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.698)").s().p("EluSDxbMAAAni1MLclAAAMAAAHi1g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2344.3,-1545.1,4688.6,3090.2);


(lib.PatQuote_3 = function() {
	this.initialize();

	// Layer 2
	this.instance = new lib.Pat_3();
	this.instance.setTransform(-327.4,-97.8);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-327.4,-97.8,714,196);


(lib.PatQuote_2 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.Pat_2();
	this.instance.setTransform(-327.4,-97.8);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-327.4,-97.8,714,196);


(lib.PatQuote_1 = function() {
	this.initialize();

	// Layer 2
	this.instance = new lib.Pat_1();
	this.instance.setTransform(-224.5,-97.8);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-224.5,-97.8,687,196);


(lib.JoseQuote2 = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgSA3IgLgEQgNgIgIgOIgDgGQgFgLAAgMQAAgLAFgLIADgGQAIgOANgIQAOgIAPAAQAQAAANAIQAOAIAIAOQAIANAAAPQAAAQgIANQgIAOgOAIIgKAEQgJAEgKAAQgJAAgJgEgAgUglQgKAGgGAJQgGALAAALQAAAMAGAKQAGALAKAFQAJAHALgBQAMABAJgHQAKgFAGgLQAGgKAAgMQAAgLgGgLQgGgJgKgGQgJgHgMAAQgLAAgJAHgAAIAcIgDgEIgDgGIgEgKIgDgDIAAAXIgQAAIAAg7IAXAAQAJABAFAEQAGAGAAAJQgBAGgDAFQgEACgGABIAEAEIAEAEIAEAHIAFAIIABACgAgFgGIAEAAQADABABgCQABAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgEgCgCQgCgBgCAAIgEAAg");
	this.shape.setTransform(106.8,-35.5);

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.bf(img.Jose_2, null, new cjs.Matrix2D(1,0,0,1,-568,-74.3)).s().p("AR/E7Mgk/AAAIAAp0MAk/AAAIBCAAIAAJ0g");
	this.shape_1.setTransform(250.5,-23);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFCC").s().p("AUEFtIhQAAMgm8AAAIAArZMAm8AAAIBQAAIAFAAIAABWMgk/AAAIAAJ0MAk/AAAIAAAPg");
	this.shape_2.setTransform(236.7,-26.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.bf(img.Jose_2, null, new cjs.Matrix2D(1,0,0,1,-767.4,-98)).s().p("AknPUIAAtyIAGAAIAAgPIBBAAIAAp0IhBAAIAAhWIgGAAIAAlbIJPAAIAAemg");
	this.shape_3.setTransform(394.8,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.bf(img.Jose_2, null, new cjs.Matrix2D(1,0,0,1,-725.7,-98)).s().p("AgnPUIAAtyIBOAAIAANygAgnp3IAAlbIBOAAIAAFbg");
	this.shape_4.setTransform(361.2,0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.bf(img.Jose_2, null, new cjs.Matrix2D(1,0,0,1,-344.9,-98)).s().p("Eg13APUIAA+mMBrvAAAIAAFbMgm+AAAIAALZMAm+AAAIAANyg");
	this.shape_5.setTransform(12.3,0.2);

	this.addChild(this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-332.6,-97.8,757,196);


(lib.JoseQuote_3 = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Jose_3, null, new cjs.Matrix2D(1,0,0,1,-228.8,-104.3)).s().p("AgSAnQgKgGgGgLQgFgKgBgMQABgLAFgKQAGgKAKgGQAJgGAKgBQANABAKAGQAJAGAGAKIACADIAAAmIgCACQgGALgJAGQgKAGgNAAQgKAAgJgGgAAAAIIAEALIADAFIADAFIASAAIgBgDIgEgHIgFgIIgDgEIgFgEQAGAAAEgDQADgEABgHQAAgJgGgFQgEgFgKAAIgWAAIAAA7IAPAAIAAgYIADADgAgDgFIAAgNIADAAQAEAAACACQACABAAAEQAAABgBAAQAAABAAAAQAAABgBAAQAAABAAAAQgCACgEAAg");
	this.shape.setTransform(-110.2,-34.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.bf(img.Jose_3, null, new cjs.Matrix2D(1,0,0,1,-601.3,-79)).s().p("AACALQgEgEAAgHIAAgCIAFgKIAAAYIgBgBg");
	this.shape_1.setTransform(259.7,-58.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.bf(img.Jose_3, null, new cjs.Matrix2D(1,0,0,1,-591.1,-53.8)).s().p("AgUAnQgKgGgGgLQgGgKAAgMQAAgLAGgKQAGgKAKgGQAJgGALgBQAMABAJAGQAKAGAGAKQAGAKAAALQAAAMgGAKQgGALgKAGQgJAGgMAAQgLAAgJgGgAgCAIIAEALIADAFIADAFIASAAIgBgDIgFgHIgEgIIgEgEQgCgDgCgBQAGAAAEgDQADgEABgHQAAgJgGgFQgFgFgJAAIgXAAIAAA7IAQAAIAAgYIADADgAgFgFIAAgNIAEAAQACAAACACQACABAAAEQAAAAAAABQAAABAAAAQAAABgBAAQAAABgBAAQgBACgDAAg");
	this.shape_2.setTransform(243,-81.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("A73EiIgLgEQgNgIgIgOIgDgGQgFgLgBgNQABgMAFgKIADgHQAIgOANgIQAOgIAQAAQARAAANAIIAJAGQAHAHAFAJQAJANAAAQQAAARgJANQgFAJgHAGIgJAHIgKAEQgJAEgLAAQgLAAgIgEgA76DEQgJAFgGALQgGAKAAAMQAAANAGAKQAGALAJAFQAKAHAMgBQAMABAKgHQAKgFAGgLIABgDQAFgIAAgMQAAgKgFgJIgBgDQgGgLgKgFQgKgHgMAAQgMAAgKAHgA7bEHIgEgEIgDgGIgGgKIgDgDIAAAXIgPAAIAAg8IAYAAQAKAAAFAEQAGAGgBAJQAAAHgDAEQgFAEgFABIAEAEIAEAEIAEAHIAFAHIABADgA7rDjIAFAAQAEAAACgBQABAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAAAQAAgEgCgCQgCgBgEAAIgFAAgAbRiyIgKgEQgNgIgJgOIgDgGQgEgLgBgMQABgNAEgLIADgGQAJgOANgIQANgIARAAQAQAAANAIQAOAIAIAOQAIANABARQgBAQgIANQgIAOgOAIIgKAEQgIADgLABQgLgBgJgDgAbPkQQgKAGgFAJQgHALAAANQAAAMAHAKQAFALAKAFQAKAHAMAAQAMAAAJgHQAKgFAGgLQAGgKAAgMQAAgNgGgLQgGgJgKgGQgJgHgMAAQgMAAgKAHgAbtjNIgDgEIgDgGIgGgKIgDgEIAAAYIgPAAIAAg9IAYAAQAJABAGAFQAFAFAAAIQAAAHgEAFQgEAFgGAAQADABABADIAEAEIAEAHIAFAIIABACgAbejxIAFAAQAEABABgCQABAAAAgBQABAAAAgBQAAAAAAgBQABgBAAgBQAAgDgDgBQgCgCgDAAIgFAAg");
	this.shape_3.setTransform(66.5,-58);

	// Layer 4
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("ABLNNQgEgGgCgIQgKANgOAHQgOAGgRAAQgPAAgMgGQgMgHgFgMQgDgFgBgGIgBgPIAAiAIAbgFIAAB9QAAANACAGQADAHAEAEQAEADAGABIALACQANAAAMgJQAMgIAHgPIAAh7IAbgFIAAB/QAAAQADAJQADAJAGAFIgRATQgJgHgEgHgAMjNQQgGgGgCgKQgNANgLAFQgMAGgPAAQgVAAgMgIQgNgHgFgMQgFgLAAgMQABgeAYgQQAXgQAtgBIAJABIADAAIAAgNQAAgLgBgGQgBgGgEgEQgEgFgGgCQgFgCgIAAQgKAAgLADQgKADgKAEQgJAFgGAFIgNgTQARgMASgGQATgGATAAQASAAAMAHQAMAHAGAOQADAHABAKIAAAVIgCA6QAAAOABAIQABAIADAEQADAFAHADIgPAUQgJgDgGgHgALcMFQgOALABAUQAAAPAHAIQAIAJAPAAQANgBAMgHQALgHAGgNIABgtIgGgBIgHAAQghAAgOALgAjjNQQgGgGgDgKQgMANgMAFQgMAGgOAAQgWAAgMgIQgMgHgFgMQgFgLAAgMQAAgeAYgQQAYgQAsgBIAJABIADAAIAAgNQABgLgBgGQgCgGgDgEQgEgFgGgCQgGgCgIAAQgKAAgKADQgLADgJAEQgKAFgFAFIgOgTQARgMATgGQASgGATAAQASAAANAHQAMAHAFAOQADAHABAKIAAAVIgBA6QgBAOABAIQABAIADAEQAEAFAGADIgOAUQgJgDgGgHgAkqMFQgOALAAAUQAAAPAIAIQAHAJAPAAQAOgBALgHQALgHAHgNIABgtIgHgBIgHAAQghAAgNALgAt9NQQgGgGgCgKQgNANgLAFQgMAGgPAAQgVAAgMgIQgNgHgFgMQgFgLAAgMQABgeAYgQQAXgQAtgBIAJABIADAAIAAgNQAAgLgBgGQgBgGgEgEQgEgFgGgCQgFgCgIAAQgKAAgLADQgKADgKAEQgJAFgGAFIgNgTQARgMASgGQATgGATAAQASAAAMAHQAMAHAGAOQADAHABAKIAAAVIgCA6QAAAOABAIQABAIADAEQADAFAHADIgPAUQgJgDgGgHgAvEMFQgOALABAUQAAAPAHAIQAIAJAPAAQANgBAMgHQALgHAGgNIABgtIgGgBIgHAAQghAAgOALgA+FNQQgGgGgCgKQgNANgLAFQgMAGgPAAQgVAAgMgIQgNgHgFgMQgFgLAAgMQABgeAYgQQAXgQAtgBIAJABIADAAIAAgNQAAgLgBgGQgBgGgEgEQgEgFgGgCQgFgCgIAAQgKAAgLADQgKADgKAEQgJAFgGAFIgNgTQARgMASgGQATgGATAAQASAAAMAHQAMAHAGAOQADAHABAKIAAAVIgCA6QAAAOABAIQABAIADAEQADAFAHADIgPAUQgJgDgGgHgA/MMFQgOALABAUQAAAPAHAIQAIAJAPAAQANgBAMgHQALgHAGgNIABgtIgGgBIgHAAQghAAgOALgAh2NYIgKgEQgJgFgEgIQgEgJAAgNIAAh3IgXAAIAAgVIAXAAIABgTIABgRIABgIIAcgGIgBAHIgBAUIgBAXIAsAAIgJAVIgkAAIAABwQAAAOAFAGQAFAGAMAAIAKgBIAHgDIAEASQgGADgIACQgHACgJAAIgNgBgAsPNYIgLgEQgJgFgEgIQgEgJAAgNIAAh3IgWAAIAAgVIAWAAIABgTIABgRIABgIIAdgGIgBAHIgCAUIgBAXIAsAAIgIAVIglAAIAABwQAAAOAFAGQAFAGANAAIAJgBIAIgDIAEASQgHADgHACQgIACgJAAIgMgBgAz/NYIgKgEQgJgFgEgIQgEgJAAgNIAAh3IgXAAIAAgVIAXAAIABgTIABgRIABgIIAcgGIgBAHIgBAUIgBAXIAsAAIgJAVIgkAAIAABwQAAAOAFAGQAFAGAMAAIAKgBIAHgDIAEASQgGADgIACQgHACgJAAIgNgBgA4DNUQgQgFgOgIIAKgUQAOAIANAEQAOAEAPAAQAQAAAJgIQAKgIAAgOQAAgMgHgHQgHgHgPgDIgVgEQgWgFgLgMQgLgNAAgSQAAgQAIgMQAHgMAOgHQAOgHATAAQANAAAOAEQAOAEAMAGIgLAVQgLgGgKgDQgLgEgLAAQgPAAgJAIQgJAIAAANQAAAKAGAGQAFAGAOADIAXAFQAYAFALAMQAMAMAAATQAAASgJAMQgIANgPAHQgOAHgUABQgRgBgRgEgA8XNYIgLgEQgJgFgEgIQgEgJAAgNIAAh3IgWAAIAAgVIAWAAIABgTIABgRIABgIIAdgGIgBAHIgCAUIgBAXIAsAAIgIAVIglAAIAABwQAAAOAFAGQAFAGANAAIAJgBIAIgDIAEASQgHADgHACQgIACgJAAIgMgBgAXHNRQgHgHAAgKQAAgKAGgHQAHgGAKAAQAKAAAHAGQAHAHAAAKQAAAKgHAHQgHAHgKAAQgKAAgGgHgAQ7M+QgUgYAAgsQAAgVAFgQQAFgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAIAIAEAJQAFAJABAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAIALALAFQAMAGANgBQANAAAKgEQALgEAJgIIAKARQgMALgPAGQgPAFgRAAQgkAAgVgZgASWLsQAAgOgCgJQgCgKgEgGQgEgHgJgEQgIgEgKAAQgTAAgKANQgLAOgBAbIBQAAIAAAAgAIfM9QgJgNgEgPQgEgPAAgTQAAgcAHgSQAIgRALgLQAKgLAMgFQAMgFANAAQARAAALAGQALAFAJAIIgPATQgJgHgHgEQgIgDgJAAQgLAAgJAFQgIAGgFAJQgFAJgDAOQgCAPAAATQAAAdALAQQALAPAVAAQALAAAJgEQAKgFAIgJIAPARQgMAMgNAGQgMAFgRAAQglAAgSgagAEbM+QgUgYAAgsQAAgVAFgQQAFgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAIAIAEAJQAFAJABAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAIALALAFQAMAGANgBQANAAAKgEQALgEAJgIIAKARQgMALgPAGQgPAFgRAAQgkAAgVgZgAF2LsQAAgOgCgJQgCgKgEgGQgEgHgJgEQgIgEgKAAQgTAAgKANQgLAOgBAbIBQAAIAAAAgAn3M+QgUgYAAgsQAAgVAFgQQAFgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAIAIAEAJQAFAJABAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAIALALAFQAMAGANgBQANAAAKgEQALgEAJgIIAKARQgMALgPAGQgPAFgRAAQgkAAgVgZgAmcLsQAAgOgCgJQgCgKgEgGQgEgHgJgEQgIgEgKAAQgTAAgKANQgLAOgBAbIBQAAIAAAAgAPlNVQgFgCgEgEQgEgDgDgGQgCgGAAgJIAAi5QAAgRgCgKIgCgJIAbgFIADALQACAKAAAUIAACyQAAAKACAEQACAEAGAAIACgBIABAAIAGASIgJADIgJABQgGAAgFgCgAOHNVQgFgCgEgEQgEgDgDgGQgCgGAAgJIAAi5QAAgRgCgKIgCgJIAbgFIADALQACAKAAAUIAACyQAAAKACAEQACAEAGAAIACgBIABAAIAGASIgJADIgJABQgGAAgFgCgATwM/QgSgXgBgrQAAgbAKgVQAJgUASgNQAIgFAIgDQAIgCAJAAQAPAAAMAFQAMAGAIALIAAgFIAAgKIAAgMIAAhJIAbAEIAADDQAAAWACAOQABANADAHIgcAAIgCgFIgCgNQgKALgKAFQgLAFgPAAQgjgBgSgWgAUVK9QgJAEgFAJQgGAKgDALQgDAMABASQgBAPACALQABAMAFAHQAGALAIAFQAJAFAMAAQAKAAAIgDQAHgDAIgGQAGgEACgEIADgEIAAhdQgHgJgKgEQgKgFgQAAQgKAAgIAFgACgNTIAAiGQAAgTgDgJIgDgJIAbgIIACAEQACAEABAHQABAGAAAIQAJgOANgIQANgHAOAAIAGAAIADABIgLAeIgDgBIgFAAQgHAAgIADQgIADgGAGQgFAGgDAGQgCAGAAAKIAABtgApqNTIAAiZIgRAAIAAgVIARAAIAAgbQAAgNADgJQAEgIAEgFIAIgIQAHgFAHgCQAHgCAKAAQALAAAKACQAKADAIAFIgKATIgMgFQgHgDgHAAQgMAAgGAIQgGAIAAAPIAAAbIAwAAIgIAVIgoAAIAACZgAxBNTIAAh4QAAgKgCgGQgBgHgEgDQgDgDgFgCQgFgCgHAAQgNAAgNAHQgNAIgMAOIAAB8IgbAAIAAjXQAAgRgCgJIgDgJIAcgGIACALQACALAAAUIAAAoIAAALIgBAJIAAAEQAMgLAPgIQAOgIARgBQARABAMAHQAMAIAEAMIACAKIABAPIAAB9gA5yNTIAAitIAcgFIAACygEghJANTIAAh4QAAgKgCgGQgBgHgEgDQgDgDgFgCQgFgCgHAAQgNAAgNAHQgNAIgMAOIAAB8IgbAAIAAjXQAAgRgCgJIgDgJIAcgGIACALQACALAAAUIAAAoIAAALIgBAJIAAAEQAMgLAPgIQAOgIARgBQARABAMAHQAMAIAEAMIACAKIABAPIAAB9gEgk4ANTIgeiFIgHghIgEgXIgCgMIgCALIgEAYIgGAfIgdCHIglAAIg5jwIAfAAIAeCMIAGAgIAFAbIACAOIACgIIADgRIAEgWIAFgWIAgiQIAgAAIAiCVIAGAgIAEAWIACAKIACgMIAFgbIAHgjIAdiLIAdAAIg3DwgAXJMFQgFgUADgSQAEgSAPgOIAOgLQAHgFAFgIQAFgHAAgLQAAgNgJgIQgJgIgNAAQgNAAgLAEQgLAEgNAIIgMgTQANgKARgFQARgGASAAQAYAAAPAOQAOAOABAXQAAANgFAKQgFAKgHAHIgMALIgIAGQgMAKgEAOQgEAPAFASgA5yJ+QgGgGgBgJQABgJAGgGQAGgGAJAAQAJAAAGAGQAGAGAAAJQAAAJgGAGQgGAGgJAAQgJAAgGgGgAi2FoQgEgGgCgIQgKANgNAHQgOAGgSAAQgQAAgMgGQgMgHgGgMQgCgFgBgGIgBgPIAAiAIAbgFIAAB9QAAANACAGQACAHAGAEQAEADAGABIALACQAOAAAMgJQAMgIAHgPIAAh7IAbgFIAAB/QAAAQACAJQADAJAHAFIgSATQgIgHgFgHgAnmFrQgGgGgCgKQgNANgLAFQgMAGgPAAQgVAAgMgIQgNgHgFgMQgFgLAAgMQABgeAYgQQAXgQAtgBIAJABIADAAIAAgNQAAgLgBgGQgBgGgEgEQgEgFgGgCQgFgCgIAAQgKAAgLADQgKADgKAEQgJAFgGAFIgNgTQARgMASgGQATgGATAAQASAAAMAHQAMAHAGAOQADAHABAKIAAAVIgCA6QAAAOABAIQABAIADAEQADAFAHADIgPAUQgJgDgGgHgAotEgQgOALABAUQAAAPAHAIQAIAJAPAAQANgBAMgHQALgHAGgNIABgtIgGgBIgHAAQghAAgOALgEglrAFrQgGgGgCgKQgNANgLAFQgMAGgPAAQgVAAgMgIQgNgHgFgMQgFgLAAgMQABgeAYgQQAXgQAtgBIAJABIADAAIAAgNQAAgLgBgGQgBgGgEgEQgEgFgGgCQgFgCgIAAQgKAAgLADQgKADgKAEQgJAFgGAFIgNgTQARgMASgGQATgGATAAQASAAAMAHQAMAHAGAOQADAHABAKIAAAVIgCA6QAAAOABAIQABAIADAEQADAFAHADIgPAUQgJgDgGgHgEgmyAEgQgOALABAUQAAAPAHAIQAIAJAPAAQANgBAMgHQALgHAGgNIABgtIgGgBIgHAAQghAAgOALgAl4FzIgLgEQgJgFgEgIQgEgJAAgNIAAh3IgWAAIAAgVIAWAAIABgTIABgRIABgIIAdgGIgBAHIgCAUIgBAXIAsAAIgIAVIglAAIAABwQAAAOAFAGQAFAGANAAIAJgBIAIgDIAEASQgHADgHACQgIACgJAAIgMgBgAwSFzIgKgEQgJgFgEgIQgEgJAAgNIAAh3IgXAAIAAgVIAXAAIABgTIABgRIABgIIAcgGIgBAHIgBAUIgBAXIAsAAIgJAVIgkAAIAABwQAAAOAFAGQAFAGAMAAIAKgBIAHgDIAEASQgGADgIACQgHACgJAAIgNgBgADFFsQgGgHAAgKQAAgKAGgHQAHgGAKAAQAKAAAHAGQAGAHAAAKQAAAKgGAHQgHAHgKAAQgKAAgHgHgAAZFZQgUgYgBgsQAAgVAFgQQAGgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAHAIAFAJQAEAJACAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAHALAMAFQALAGANgBQANAAAKgEQALgEAJgIIALARQgMALgPAGQgPAFgRAAQglAAgUgZgAB0EHQAAgOgCgJQgCgKgEgGQgFgHgIgEQgJgEgKAAQgTAAgKANQgKAOgBAbIBQAAIAAAAgAr5FZQgUgYgBgsQAAgVAFgQQAGgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAHAIAFAJQAEAJACAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAHALAMAFQALAGANgBQANAAAKgEQALgEAJgIIALARQgMALgPAGQgPAFgRAAQglAAgUgZgAqeEHQAAgOgCgJQgCgKgEgGQgFgHgIgEQgJgEgKAAQgTAAgKANQgKAOgBAbIBQAAIAAAAgA2cFZQgUgYgBgsQAAgVAFgQQAGgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAHAIAFAJQAEAJACAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAHALAMAFQALAGANgBQANAAAKgEQALgEAJgIIALARQgMALgPAGQgPAFgRAAQglAAgUgZgA1BEHQAAgOgCgJQgCgKgEgGQgFgHgIgEQgJgEgKAAQgTAAgKANQgKAOgBAbIBQAAIAAAAgA7EFZQgUgYgBgsQAAgVAFgQQAGgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAHAIAFAJQAEAJACAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAHALAMAFQALAGANgBQANAAAKgEQALgEAJgIIALARQgMALgPAGQgPAFgRAAQglAAgUgZgA5pEHQAAgOgCgJQgCgKgEgGQgFgHgIgEQgJgEgKAAQgTAAgKANQgKAOgBAbIBQAAIAAAAgEgjAAFaQgSgXgBgrQAAgbAKgVQAJgUASgNQAIgFAIgDQAIgCAJAAQAPAAAMAFQAMAGAIALIAAgFIAAgKIAAgMIAAhJIAbAEIAADDQAAAWACAOQABANADAHIgcAAIgCgFIgCgNQgKALgKAFQgLAFgPAAQgjgBgSgWgEgibADYQgJAEgFAJQgGAKgDALQgDAMABASQgBAPACALQABAMAFAHQAGALAIAFQAJAFAMAAQAKAAAIgDQAHgDAIgGQAGgEACgEIADgEIAAhdQgHgJgKgEQgKgFgQAAQgKAAgIAFgAhhFuIAAiGQAAgTgDgJIgDgJIAcgIIABAEQACAEABAHQACAGgBAIQAKgOANgIQANgHANAAIAHAAIADABIgLAeIgEgBIgEAAQgIAAgHADQgIADgGAGQgGAGgCAGQgCAGAAAKIAABtgAtsFuIAAiZIgRAAIAAgVIARAAIAAgbQAAgNADgJQADgIAFgFIAIgIQAGgFAIgCQAHgCAKAAQALAAAKACQAJADAIAFIgKATIgMgFQgHgDgHAAQgMAAgGAIQgGAIAAAPIAAAbIAxAAIgJAVIgoAAIAACZgAyLFuIAAh2IgBgOIgBgJIgEgGQgDgDgFgCQgGgCgGAAQgHAAgJADQgIADgJAGQgIAGgHAGIAACCIgbAAIAAiGQAAgTgDgJIgDgJIAagHIADAIQADAIABALQANgOAOgGQAOgHAOAAQAOAAAMAHQALAHAFALIAEAKIABALIAACEgA4YFuIAAiGQAAgTgDgJIgDgJIAcgIIABAEQACAEABAHQACAGgBAIQAKgOANgIQANgHANAAIAHAAIADABIgLAeIgEgBIgEAAQgIAAgHADQgIADgGAGQgGAGgCAGQgCAGAAAKIAABtgA83FuIAAiZIgRAAIAAgVIARAAIAAgbQAAgNADgJQADgIAFgFIAIgIQAGgFAIgCQAHgCAKAAQALAAAKACQAJADAIAFIgKATIgMgFQgHgDgHAAQgMAAgGAIQgGAIAAAPIAAAbIAxAAIgJAVIgoAAIAACZgA+hFuIAAiZIgRAAIAAgVIARAAIAAgbQAAgNADgJQAEgIAEgFIAIgIQAHgFAHgCQAHgCAKAAQALAAAKACQAKADAIAFIgKATIgMgFQgHgDgHAAQgMAAgGAIQgGAIAAAPIAAAbIAwAAIgIAVIgoAAIAACZgEggAAFuIAAitIAcgFIAACygEggAACZQgGgGgBgJQABgJAGgGQAGgGAJAAQAJAAAGAGQAGAGAAAJQAAAJgGAGQgGAGgJAAQgJAAgGgGgAYqhAQALgDAIgGQAHgFAFgLQAFgLAFgRIgMACIgEgSIgGgXIgHgWIglhtIAagJIAkBxIAFASIAEARIACAIIAAAAIACgGIAFgPIAEgQIAihyIAgAAIg8C1QgIAagNARQgNAQgXAGgEAhLgB4QgGgGgDgKQgMANgMAFQgMAGgOAAQgWAAgMgIQgMgHgFgMQgFgLAAgMQAAgeAYgQQAYgQAsgBIAJABIADAAIAAgNQABgLgBgGQgCgGgDgEQgEgFgGgCQgGgCgIAAQgKAAgKADQgLADgJAEQgKAFgFAFIgOgTQARgMATgGQASgGATAAQASAAANAHQAMAHAFAOQADAHABAKIAAAVIgBA6QgBAOABAIQABAIADAEQAEAFAGADIgOAUQgJgDgGgHgEAgEgDDQgOALAAAUQAAAPAIAIQAHAJAPAAQAOgBALgHQALgHAHgNIABgtIgHgBIgHAAQghAAgNALgAISh4QgGgGgCgKQgNANgLAFQgMAGgPAAQgVAAgMgIQgNgHgFgMQgFgLAAgMQABgeAYgQQAXgQAtgBIAJABIADAAIAAgNQAAgLgBgGQgBgGgEgEQgEgFgGgCQgFgCgIAAQgKAAgLADQgKADgKAEQgJAFgGAFIgNgTQARgMASgGQATgGATAAQASAAAMAHQAMAHAGAOQADAHABAKIAAAVIgCA6QAAAOABAIQABAIADAEQADAFAHADIgPAUQgJgDgGgHgAHLjDQgOALABAUQAAAPAHAIQAIAJAPAAQANgBAMgHQALgHAGgNIABgtIgGgBIgHAAQghAAgOALgA15h4QgGgGgCgKQgNANgLAFQgMAGgPAAQgVAAgMgIQgNgHgFgMQgFgLAAgMQABgeAYgQQAXgQAtgBIAJABIADAAIAAgNQAAgLgBgGQgBgGgEgEQgEgFgGgCQgFgCgIAAQgKAAgLADQgKADgKAEQgJAFgGAFIgNgTQARgMASgGQATgGATAAQASAAAMAHQAMAHAGAOQADAHABAKIAAAVIgCA6QAAAOABAIQABAIADAEQADAFAHADIgPAUQgJgDgGgHgA3AjDQgOALABAUQAAAPAHAIQAIAJAPAAQANgBAMgHQALgHAGgNIABgtIgGgBIgHAAQghAAgOALgA/5h7QgSgMgJgVQgKgVAAgdQAAgbAIgWQAJgXAQgUQAWgZAYgOQAXgPAagHIAHASQgTAGgQAJQgQAKgNALQgMAMgIAMQgGAKgDAKIgFAQIgCAHQAJgIAOgFQAOgFAOAAQARAAAQAIQAQAIAKAPQAKAPABAXQgBAWgKARQgJARgSAKQgRAKgWAAQgYAAgSgMgA/ljmQgMAFgMAIIAAAGIgBAMQAAARADAMQADAMAGAJQAHAJAIAEQAJAEALAAQAVAAAMgPQAMgOAAgZQAAgRgGgKQgFgLgKgGQgKgFgNAAQgLAAgMAFgARbhwIgLgEQgJgFgEgIQgEgJAAgNIAAh3IgWAAIAAgVIAWAAIABgTIABgRIABgIIAdgGIgBAHIgCAUIgBAXIAsAAIgIAVIglAAIAABwQAAAOAFAGQAFAGANAAIAJgBIAIgDIAEASQgHADgHACQgIACgJAAIgMgBgAEGhwIgKgEQgJgFgEgIQgEgJAAgNIAAh3IgXAAIAAgVIAXAAIABgTIABgRIABgIIAcgGIgBAHIgBAUIgBAXIAsAAIgJAVIgkAAIAABwQAAAOAFAGQAFAGAMAAIAKgBIAHgDIAEASQgGADgIACQgHACgJAAIgNgBgEAlMgCKQgUgYAAgsQAAgVAFgQQAFgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAIAIAEAJQAFAJABAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAIALALAFQAMAGANgBQANAAAKgEQALgEAJgIIAKARQgMALgPAGQgPAFgRAAQgkAAgVgZgEAmngDcQAAgOgCgJQgCgKgEgGQgEgHgJgEQgIgEgKAAQgTAAgKANQgLAOgBAbIBQAAIAAAAgAWAiKQgUgYgBgsQAAgVAFgQQAGgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAHAIAFAJQAEAJACAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAHALAMAFQALAGANgBQANAAAKgEQALgEAJgIIALARQgMALgPAGQgPAFgRAAQglAAgUgZgAXbjcQAAgOgCgJQgCgKgEgGQgFgHgIgEQgJgEgKAAQgTAAgKANQgKAOgBAbIBQAAIAAAAgAiCiKQgUgYgBgsQAAgVAFgQQAGgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAHAIAFAJQAEAJACAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAHALAMAFQALAGANgBQANAAAKgEQALgEAJgIIALARQgMALgPAGQgPAFgRAAQglAAgUgZgAgnjcQAAgOgCgJQgCgKgEgGQgFgHgIgEQgJgEgKAAQgTAAgKANQgKAOgBAbIBQAAIAAAAgAmqiKQgUgYgBgsQAAgVAFgQQAGgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAHAIAFAJQAEAJACAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAHALAMAFQALAGANgBQANAAAKgEQALgEAJgIIALARQgMALgPAGQgPAFgRAAQglAAgUgZgAlPjcQAAgOgCgJQgCgKgEgGQgFgHgIgEQgJgEgKAAQgTAAgKANQgKAOgBAbIBQAAIAAAAgAyriKQgUgYgBgsQAAgVAFgQQAGgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAHAIAFAJQAEAJACAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAHALAMAFQALAGANgBQANAAAKgEQALgEAJgIIALARQgMALgPAGQgPAFgRAAQglAAgUgZgAxQjcQAAgOgCgJQgCgKgEgGQgFgHgIgEQgJgEgKAAQgTAAgKANQgKAOgBAbIBQAAIAAAAgAMviJQgSgXgBgrQAAgbAKgVQAJgUASgNQAIgFAIgDQAIgCAJAAQAPAAAMAFQAMAGAIALIAAgFIAAgKIAAgMIAAhJIAbAEIAADDQAAAWACAOQABANADAHIgcAAIgCgFIgCgNQgKALgKAFQgLAFgPAAQgjgBgSgWgANUkLQgJAEgFAJQgGAKgDALQgDAMABASQgBAPACALQABAMAFAHQAGALAIAFQAJAFAMAAQAKAAAIgDQAHgDAIgGQAGgEACgEIADgEIAAhdQgHgJgKgEQgKgFgQAAQgKAAgIAFgAumiJQgSgXgBgrQAAgbAKgVQAJgUASgNQAIgFAIgDQAIgCAJAAQAPAAAMAFQAMAGAIALIAAgFIAAgKIAAgMIAAhJIAbAEIAADDQAAAWACAOQABANADAHIgcAAIgCgFIgCgNQgKALgKAFQgLAFgPAAQgjgBgSgWgAuBkLQgJAEgFAJQgGAKgDALQgDAMABASQgBAPACALQABAMAFAHQAGALAIAFQAJAFAMAAQAKAAAIgDQAHgDAIgGQAGgEACgEIADgEIAAhdQgHgJgKgEQgKgFgQAAQgKAAgIAFgA9BiLQgUgYgBgsQABgdAJgUQAKgUARgLQASgLAYAAQAlAAAVAYQAUAZAAArQAAAdgJAUQgKAVgSALQgRALgYAAQgmgBgUgYgA8IkUQgYAAgMAQQgNAPAAAhQAAAoAMARQAMASAbAAQAYAAAMgPQANgQAAghQAAgngMgSQgMgSgZAAIgCAAgEAjAgBzIg/ivIAcgGIApB4IAEAOIADAMIABAEIABAAIACgJIAGgUIAoh0IAdAAIhBCwgEgiygB1Ig/AAIAAjwIAwAAQASAAANABQANABALAEQALAEALAJQAUAOAKAaQALAaAAAkQgBAfgHAWQgIAXgMANQgPARgSAHQgQAGgXAAIgDAAgEgjUgCNIAcAAQANABALgCQAMgCAJgFQAKgGAGgLQAIgOAEgRQAEgRAAgTQABgbgFgSQgEgTgMgOQgMgOgNgEQgNgFgTABIgcAAgAeHh1IAAh4QAAgKgCgGQgCgHgDgDQgDgDgGgCQgFgCgGAAQgNAAgNAHQgOAIgLAOIAAB8IgcAAIAAjXQAAgRgCgJIgCgJIAbgGIADALQABALABAUIAAAoIgBALIAAAJIAAAEQAMgLAOgIQAPgIARgBQAQABAMAHQANAIAEAMIACAKIABAPIAAB9gAUZh1IAAh4QAAgKgCgGQgCgHgDgDQgDgDgGgCQgFgCgGAAQgNAAgNAHQgOAIgLAOIAAB8IgcAAIAAjXQAAgRgCgJIgCgJIAbgGIADALQABALABAUIAAAoIgBALIAAAJIAAAEQAMgLAOgIQAPgIARgBQAQABAMAHQANAIAEAMIACAKIABAPIAAB9gALJh1IAAh2IgBgOIgBgJIgEgGQgDgDgFgCQgGgCgGAAQgHAAgJADQgIADgJAGQgIAGgHAGIAACCIgbAAIAAiGQAAgTgDgJIgDgJIAagHIADAIQADAIABALQANgOAOgGQAOgHAOAAQAOAAAMAHQALAHAFALIAEAKIABALIAACEgACNh1IAAh2IgBgOIgBgJIgEgGQgDgDgFgCQgGgCgGAAQgHAAgJADQgIADgJAGQgIAGgHAGIAACCIgbAAIAAiGQAAgTgDgJIgDgJIAagHIADAIQADAIABALQANgOAOgGQAOgHAOAAQAOAAAMAHQALAHAFALIAEAKIABALIAACEgAj+h1IAAiGQAAgTgDgJIgDgJIAcgIIABAEQACAEABAHQACAGgBAIQAKgOANgIQANgHANAAIAHAAIADABIgLAeIgEgBIgEAAQgIAAgHADQgIADgGAGQgGAGgCAGQgCAGAAAKIAABtgAodh1IAAiZIgRAAIAAgVIARAAIAAgbQAAgNADgJQADgIAFgFIAIgIQAGgFAIgCQAHgCAKAAQALAAAKACQAJADAIAFIgKATIgMgFQgHgDgHAAQgMAAgGAIQgGAIAAAPIAAAbIAxAAIgJAVIgoAAIAACZgAqHh1IAAiZIgRAAIAAgVIARAAIAAgbQAAgNADgJQAEgIAEgFIAIgIQAHgFAHgCQAHgCAKAAQALAAAKACQAKADAIAFIgKATIgMgFQgHgDgHAAQgMAAgGAIQgGAIAAAPIAAAbIAwAAIgIAVIgoAAIAACZgArmh1IAAitIAcgFIAACygA0nh1IAAiGQAAgTgDgJIgDgJIAcgIIABAEQACAEABAHQACAGgBAIQAKgOANgIQANgHANAAIAHAAIADABIgLAeIgEgBIgEAAQgIAAgHADQgIADgGAGQgGAGgCAGQgCAGAAAKIAABtgEglQgB1IAAh0IhmAAIAAB0IgcAAIAAjwIAcAAIAABlIBmAAIAAhlIAcAAIAADwgArmlKQgGgGgBgJQABgJAGgGQAGgGAJAAQAJAAAGAGQAGAGAAAJQAAAJgGAGQgGAGgJAAQgJAAgGgGgAXQoaIgNgDIgFgVIAMAEIAOABQAWAAARgIQARgJAKgOQAKgOAAgSQAAgWgOgMQgNgMgZAAQgNAAgMACQgMACgIAEIAMh2IBnAAIgEAXIhLAAIgGBEIAIgBIAQgBQAVAAAQAIQARAHAJAPQAKAPAAAWQAAAZgOATQgOATgXAKQgWAKgcAAIgNgBgAUEpYQgTgFgRgLIAMgXQAPALAQAFQAQAFARAAQAOAAAJgCQAIgDAIgFQAIgHAFgJQAEgIAAgLQAAgQgLgLQgLgLgVgHIgYgHQgQgFgKgFQgKgEgHgHQgHgIgEgKQgEgKAAgMQAAgUAKgQQAJgPASgJQARgIAXgBQAUAAASAGQASAGARALIgNAVQgLgHgJgFQgKgEgJgCQgJgCgKAAQgXAAgMAKQgNALAAASQAAAPAJAJQAKAJAVAHIAcAIQAPAFAKAGQAKAFAHAJQAHAIAEALQAFALAAAMQgBARgIAPQgIAPgRALQgLAHgNAEQgNADgRAAQgVAAgTgFgEAhMgJdQgGgGgDgKQgMANgMAFQgMAGgOAAQgWAAgMgIQgMgHgFgMQgFgLAAgMQAAgeAYgQQAYgQAsgBIAJABIADAAIAAgNQABgLgBgGQgCgGgDgEQgEgFgGgCQgGgCgIAAQgKAAgKADQgLADgJAEQgKAFgFAFIgOgTQARgMATgGQASgGATAAQASAAANAHQAMAHAFAOQADAHABAKIAAAVIgBA6QgBAOABAIQABAIADAEQAEAFAGADIgOAUQgJgDgGgHgEAgFgKoQgOALAAAUQAAAPAIAIQAHAJAPAAQAOgBALgHQALgHAHgNIABgtIgHgBIgHAAQghAAgNALgAltpdQgGgGgCgKQgNANgLAFQgMAGgPAAQgVAAgMgIQgNgHgFgMQgFgLAAgMQABgeAYgQQAXgQAtgBIAJABIADAAIAAgNQAAgLgBgGQgBgGgEgEQgEgFgGgCQgFgCgIAAQgKAAgLADQgKADgKAEQgJAFgGAFIgNgTQARgMASgGQATgGATAAQASAAAMAHQAMAHAGAOQADAHABAKIAAAVIgCA6QAAAOABAIQABAIADAEQADAFAHADIgPAUQgJgDgGgHgAm0qoQgOALABAUQAAAPAHAIQAIAJAPAAQANgBAMgHQALgHAGgNIABgtIgGgBIgHAAQghAAgOALgAHqpVIgKgEQgJgFgEgIQgEgJAAgNIAAh3IgXAAIAAgVIAXAAIABgTIABgRIABgIIAcgGIgBAHIgBAUIgBAXIAsAAIgJAVIgkAAIAABwQAAAOAFAGQAFAGAMAAIAKgBIAHgDIAEASQgGADgIACQgHACgJAAIgNgBgAtQpVIgLgEQgJgFgEgIQgEgJAAgNIAAh3IgWAAIAAgVIAWAAIABgTIABgRIABgIIAdgGIgBAHIgCAUIgBAXIAsAAIgIAVIglAAIAABwQAAAOAFAGQAFAGANAAIAJgBIAIgDIAEASQgHADgHACQgIACgJAAIgMgBgA2OpVIgKgEQgJgFgEgIQgEgJAAgNIAAh3IgXAAIAAgVIAXAAIABgTIABgRIABgIIAcgGIgBAHIgBAUIgBAXIAsAAIgJAVIgkAAIAABwQAAAOAFAGQAFAGAMAAIAKgBIAHgDIAEASQgGADgIACQgHACgJAAIgNgBgAADpuQgRgYAAgsQAAgrASgYQATgYAjAAQAWAAAOAIQAPAJAJANQAIAMAEAQQAEAQAAAVQAAAdgKAUQgJAUgRAKQgRAKgWAAQgkAAgUgZgAAkryQgJAFgFAJQgEAIgCALQgCALAAAPQAAATACAPQADAPAFAJQAFAIAKAEQAJAFAMAAQANAAAKgHQAKgHAEgMQADgIACgJIABgVQAAgSgCgNQgCgNgEgJQgGgLgKgGQgKgFgLAAQgMAAgKAFgA+lpuQgTgYAAgsQAAgrAUgYQATgYAjAAQAWAAAOAIQAPAJAJANQAIAMAEAQQAEAQAAAVQAAAdgKAUQgJAUgRAKQgRAKgWAAQgkAAgUgZgA+EryQgJAFgFAJQgEAIgCALQgCALAAAPQAAATACAPQADAPAFAJQAFAIAKAEQAJAFAMAAQANAAAKgHQAKgHAEgMQADgIACgJIABgVQAAgSgCgNQgCgNgEgJQgGgLgKgGQgKgFgLAAQgMAAgKAFgAMPpvQgUgYAAgsQAAgVAFgQQAFgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAIAIAEAJQAFAJABAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAIALALAFQAMAGANgBQANAAAKgEQALgEAJgIIAKARQgMALgPAGQgPAFgRAAQgkAAgVgZgANqrBQAAgOgCgJQgCgKgEgGQgEgHgJgEQgIgEgKAAQgTAAgKANQgLAOgBAbIBQAAIAAAAgAqApvQgUgYgBgsQAAgVAFgQQAGgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAHAIAFAJQAEAJACAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAHALAMAFQALAGANgBQANAAAKgEQALgEAJgIIALARQgMALgPAGQgPAFgRAAQglAAgUgZgAolrBQAAgOgCgJQgCgKgEgGQgFgHgIgEQgJgEgKAAQgTAAgKANQgKAOgBAbIBQAAIAAAAgAxppvQgUgYAAgsQAAgVAFgQQAFgQALgNQAKgMANgGQANgGAQAAQAOAAAMAFQAMAFAJAJQAIAIAEAJQAFAJABAOQACANAAAVIAAAEIhtAAIAAAEQAAAMACAKQACAJAEAHQAIALALAFQAMAGANgBQANAAAKgEQALgEAJgIIAKARQgMALgPAGQgPAFgRAAQgkAAgVgZgAwOrBQAAgOgCgJQgCgKgEgGQgEgHgJgEQgIgEgKAAQgTAAgKANQgLAOgBAbIBQAAIAAAAgEAlpgJuQgTgXAAgrQAAgbAJgVQAJgUASgNQAIgFAIgDQAIgCAKAAQAOAAANAFQAMAGAIALIAAgFIAAgKIAAgMIAAhJIAbAEIAADDQAAAWABAOQABANADAHIgcAAIgCgFIgCgNQgJALgLAFQgLAFgPAAQgigBgSgWgEAmNgLwQgIAEgGAJQgGAKgDALQgCAMAAASQAAAPABALQACAMAEAHQAGALAJAFQAIAFAMAAQALAAAHgDQAIgDAIgGQAFgEADgEIACgEIAAhdQgGgJgLgEQgKgFgPAAQgKAAgJAFgAaEpwQgVgYAAgsQAAgdAKgUQAJgUASgLQARgLAYAAQAmAAAUAYQAVAZAAArQAAAdgKAUQgJAVgSALQgRALgYAAQgmgBgUgYgAa9r5QgYAAgNAQQgMAPAAAhQAAAoAMARQAMASAaAAQAYAAANgPQAMgQAAghQAAgngMgSQgLgSgaAAIgBAAgAkSpuQgTgXAAgrQAAgbAJgVQAJgUASgNQAIgFAIgDQAIgCAKAAQAOAAANAFQAMAGAIALIAAgFIAAgKIAAgMIAAhJIAbAEIAADDQAAAWABAOQABANADAHIgcAAIgCgFIgCgNQgJALgLAFQgLAFgPAAQgigBgSgWgAjurwQgIAEgGAJQgGAKgDALQgCAMAAASQAAAPABALQACAMAEAHQAGALAJAFQAIAFAMAAQALAAAHgDQAIgDAIgGQAFgEADgEIACgEIAAhdQgGgJgLgEQgKgFgPAAQgKAAgJAFgA5tpYIgjh7IgEgOIgBgFIgBAAIAAADIgCAIIgBAHIgjB8IgaAAIgwivIAbgGIAcB0IAFAUIABAJIABAAIACgIIAEgSIAghyIAdAAIAfB0IADALIACAKIACAEIAAAAIABgEIACgKIADgKIAbh1IAdAAIgxCwgEAkCgJaIAAh2IAAgOIgCgJIgEgGQgDgDgFgCQgFgCgGAAQgHAAgJADQgJADgIAGQgJAGgGAGIAACCIgbAAIAAiGQAAgTgDgJIgEgJIAbgHIADAIQADAIAAALQAOgOAOgGQANgHAOAAQAPAAALAHQALAHAGALIADAKIABALIAACEgASOpaIAAh0IhmAAIAAB0IgcAAIAAjwIAcAAIAABlIBmAAIAAhlIAcAAIAADwgAKopaIAAh4QAAgKgCgGQgBgHgEgDQgDgDgFgCQgFgCgHAAQgNAAgNAHQgNAIgMAOIAAB8IgbAAIAAjXQAAgRgCgJIgDgJIAcgGIACALQACALAAAUIAAAoIAAALIgBAJIAAAEQAMgLAPgIQAOgIARgBQARABAMAHQAMAIAEAMIACAKIABAPIAAB9gAEgpaIAAh2IAAgOIgCgJIgEgGQgDgDgFgCQgFgCgGAAQgHAAgJADQgJADgIAGQgJAGgGAGIAACCIgbAAIAAiGQAAgTgDgJIgEgJIAbgHIADAIQADAIAAALQAOgOAOgGQANgHAOAAQAPAAALAHQALAHAGALIADAKIABALIAACEgAr8paIAAiGQAAgTgDgJIgDgJIAcgIIABAEQACAEABAHQACAGgBAIQAKgOANgIQANgHANAAIAHAAIADABIgLAeIgEgBIgEAAQgIAAgHADQgIADgGAGQgGAGgCAGQgCAGAAAKIAABtgAzQpaIAAh4QAAgKgCgGQgBgHgEgDQgDgDgFgCQgFgCgHAAQgNAAgNAHQgNAIgMAOIAAB8IgbAAIAAjXQAAgRgCgJIgDgJIAcgGIACALQACALAAAUIAAAoIAAALIgBAJIAAAEQAMgLAPgIQAOgIARgBQARABAMAHQAMAIAEAMIACAKIABAPIAAB9gEggKgJaIAAh2IgBgOIgBgJIgEgGQgDgDgFgCQgGgCgGAAQgHAAgJADQgIADgJAGQgIAGgHAGIAACCIgbAAIAAiGQAAgTgDgJIgDgJIAagHIADAIQADAIABALQANgOAOgGQAOgHAOAAQAOAAAMAHQALAHAFALIAEAKIABALIAACEgEgi2gJaIhQhjIBChLIAjAAIhFBLIBUBjgEgkjgJaIAAjXQAAgRgCgJIgCgJIAbgGIADALQABALABAUIAADWgEgnSgJaIAAjwIAcAAIAADwg");
	this.shape_4.setTransform(56.6,-1.8);

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFCC").s().p("EAqqASIMhXLAAAMAAAgkPMBXLAAAIB4AAMAAAAkPg");
	this.shape_5.setTransform(52.7,4.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.bf(img.Jose_3, null, new cjs.Matrix2D(1,0,0,1,-817.7,-143.5)).s().p("Al0WaIAAjqIB4AAMAAAgkPIh4AAIAAk7ILpAAMAAAAs0g");
	this.shape_6.setTransform(363.1,0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.bf(img.Jose_3, null, new cjs.Matrix2D(1,0,0,1,-341.2,-143.5)).s().p("Eg1SAWaMAAAgs0MBqlAAAIAAE7MhXLAAAMAAAAkPMBXLAAAIAADqg");
	this.shape_7.setTransform(-15.4,0.2);

	this.addChild(this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-356.6,-143.3,757,287);


(lib.JoseQuote_1 = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Jose_1, null, new cjs.Matrix2D(1,0,0,1,-416.4,-95.1)).s().p("EgsrAImIAAxLMBZXAAAIAARLg");
	this.shape.setTransform(75,2.1);

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.bf(img.Jose_1, null, new cjs.Matrix2D(1,0,0,1,-808.2,-98)).s().p("AkUPUIAA+mIIpAAIAAemg");
	this.shape_1.setTransform(385.5,0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFCC").s().p("EguFAKAIAAz/IC0AAIAABQMBZXAAAIAARLMhZXAAAIAABkg");
	this.shape_2.setTransform(76.7,-1.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.bf(img.Jose_1, null, new cjs.Matrix2D(1,0,0,1,-416.4,-96.1)).s().p("EAp4AKAMhWjAAAIAAhkMBZXAAAIAABkgEgsrgIvIAAhQMBWjAAAIC0AAIAABQg");
	this.shape_3.setTransform(85.7,-1.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.bf(img.Jose_1, null, new cjs.Matrix2D(1,0,0,1,-769.5,-98)).s().p("AhsPUIAAlnICyAAIAAhkIAAxLIAAhQIiyAAIAAlAIDZAAIAAemg");
	this.shape_4.setTransform(364.8,0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.bf(img.Jose_1, null, new cjs.Matrix2D(1,0,0,1,-351.2,-98)).s().p("Eg23APUIAA+mMBtvAAAIAAFAMhWjAAAIi0AAIAAT/IC0AAMBWjAAAIAAFng");
	this.shape_5.setTransform(2.6,0.2);

	this.addChild(this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-348.7,-97.8,762,196);


(lib.DaveQuote_3 = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AoYFCIgGhLIAAgHIAAgGIgBgFIgCAIIgCAJIgWBMIgNAAIgUhJIgDgMIgCgIIgBAAIAAAFIAAAIIgBAHIgFBJIgPAAIAKhuIAVAAIATBDIADAMIABAGIAAAAIABgGIADgLIAThEIAWAAIAJBugAqrFCIAAhiIgcAAIAAgMIBKAAIgCAMIgcAAIAABigAK5jTIgGhLIAAgGIAAgHIgBgFIgCAHIgCAJIgWBNIgNAAIgUhJIgDgMIgCgIIgBAAIAAAGIAAAHIgBAHIgFBJIgPAAIAKhuIAVAAIATBEIADALIABAHIAAAAIABgIIADgKIAThEIAWAAIAJBugAImjTIAAhhIgcAAIAAgNIBKAAIgCANIgcAAIAABhg");
	this.shape.setTransform(88.8,-11.5);

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.bf(img.Dave_3, null, new cjs.Matrix2D(1,0,0,1,-780.2,-98)).s().p("AhhPUIAA+mIDCAAIAAemg");
	this.shape_1.setTransform(356.7,0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.bf(img.Dave_3, null, new cjs.Matrix2D(1,0,0,1,-744.4,-98)).s().p("AEAPUIAA+mIAEAAIAAemgAkDPUIAA+mIE/AAIAAemg");
	this.shape_2.setTransform(340.9,0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.bf(img.Dave_3, null, new cjs.Matrix2D(1,0,0,1,-656.3,-98)).s().p("AgnPUIAA+mIBOAAIAAemg");
	this.shape_3.setTransform(310.9,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.bf(img.Dave_3, null, new cjs.Matrix2D(1,0,0,1,-318.2,-98)).s().p("EgxsAPUIAA+mMBjZAAAIAAemg");
	this.shape_4.setTransform(-11.3,0.2);

	this.addChild(this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-329.5,-97.8,696.4,196);


(lib.DaveQuote_2 = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Dave_2, null, new cjs.Matrix2D(1,0,0,1,-466.8,-181.6)).s().p("AaBD0Mg18AAAIAAgMIAAncMA33AAAIAAHog");
	this.shape.setTransform(138.5,52);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("A17JJIgLgEQgNgIgHgOIgEgGQgFgLAAgNQAAgMAFgKIAEgHQAHgOANgIQAOgIARAAIAIABQAMABAKAGQANAIAIAOQAIANAAAQQAAARgIANQgIAOgNAIIgKAEIgMADIgIABQgLAAgJgEgA19HrQgKAFgGALQgFAKAAAMQAAANAFAKQAGALAKAFQAJAHANgBIAIAAQAHgCAGgEQALgFAFgLQAGgKAAgNQAAgMgGgKQgFgLgLgFQgGgEgHgCIgIgBQgNAAgJAHgA1fIuIgDgEIgDgGIgGgKIgDgDIAAAXIgQAAIAAg8IAZAAIAGAAQAFABADADQAGAGAAAJQgBAHgDAEQgEAEgGABIAEAEIAEAEIAFAHIAEAHIACADgA1uIKIAEAAQAFAAABgBQABAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgEgCgCQgBgBgFAAIgEAAgAVUnYIgKgFQgNgIgIgNIgEgHQgEgLAAgNQAAgMAEgKIAEgIQAIgNANgIQAOgIAQAAQARAAANAIQANAIAIANQAJAOAAAQQAAARgJAOQgIANgNAIIgKAFQgJACgLABQgKgBgKgCgAVTo4QgLAGgFALQgGAKAAAMQAAANAGAKQAFAKALAHQAJAFAMAAQANAAAJgFQAKgHAFgKQAHgKgBgNQABgMgHgKQgFgLgKgGQgJgFgNgBQgMABgJAFgAVwnzIgCgGIgDgFIgGgKIgDgDIAAAYIgQAAIAAg9IAZAAQAJAAAFAEQAFAGABAJQgBAGgEAEQgDAFgHABIAFADIADAFIAFAHIAEAHIACAEgAVioXIAEAAQAEAAACgCQAAAAABgBQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgEgCgCQgCgBgEAAIgEAAg");
	this.shape_1.setTransform(85,-11);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.bf(img.Dave_2, null, new cjs.Matrix2D(1,0,0,1,-393.1,-131)).s().p("EgncAMqIAA5TMBO5AAAIAAQuMg33AAAIAABjIgJgBQgQAAgOAIQgNAIgIAOIgDAHQgFAKAAANQAAAMAFALIADAHQAIANANAIIALAFQAJADAKAAIAJAAIAAERIB7AAIAAANMA18AAAIAAAugAaPqzQgNAIgIAOIgEAHQgEAKgBANQABAMAEALIAEAHQAIANANAIIAKAFQAJADALAAQALAAAJgDIAKgFQANgIAIgNQAIgOABgQQgBgRgIgNQgIgOgNgIQgNgIgRAAQgRAAgNAIgAw4HKQgKgGgGgLQgGgKAAgMQAAgNAGgKQAGgKAKgGQAJgGAMgBIAJABIAAANIgGAAIgZAAIAAA9IAQAAIAAgYIADADIAGALIADAFIADAFIAAAPIgJABQgMAAgJgGgAwpGcIAAgNIAEAAQAEAAACACQACABAAAEQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQgBACgFAAgAaXpYQgKgGgFgLQgGgKAAgMQAAgNAGgKQAFgKAKgGQAKgGAMgBQAMABAKAGQAKAGAFAKQAGAKAAANQAAAMgGAKQgFALgKAGQgKAGgMAAQgMAAgKgGgAapp3IAGALIADAFIADAFIATAAIgCgDIgEgHIgFgIIgDgEIgFgEQAGAAAEgFQAEgEAAgHQAAgJgFgFQgFgFgKAAIgYAAIAAA9IAPAAIAAgYIADADgAamqGIAAgNIAFAAQAEAAACACQACABAAAEQAAABAAAAQgBABAAAAQAAABAAAAQgBABAAAAQgCACgEAAg");
	this.shape_2.setTransform(52.5,0);

	// Layer 2
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFCC").s().p("EgncAMqIAA5TMBO5AAAIAAZTg");
	this.shape_3.setTransform(43.1,1.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.bf(img.Dave_2, null, new cjs.Matrix2D(1,0,0,1,-772.7,-129.5)).s().p("AgxUPMAAAgocIBjAAMAAAAocg");
	this.shape_4.setTransform(322.7,-0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.bf(img.Dave_2, null, new cjs.Matrix2D(1,0,0,1,-815.3,-129.5)).s().p("AjrUPMAAAgocIHXAAMAAAAocg");
	this.shape_5.setTransform(351.4,-0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.bf(img.Dave_2, null, new cjs.Matrix2D(1,0,0,1,-675.6,-129.5)).s().p("AhsUPIAAnXIAA5SIAAnzIDZAAMAAAAocg");
	this.shape_6.setTransform(306.7,-0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.bf(img.Dave_2, null, new cjs.Matrix2D(1,0,0,1,-322.8,-129.5)).s().p("EgybAUPMAAAgocMBk3AAAIAAHzMhO6AAAIAAZSMBO6AAAIAAHXg");
	this.shape_7.setTransform(-27.1,-0.2);

	this.addChild(this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-349.9,-129.7,725,259);


(lib.DaveQuote_ = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.Dave_1, null, new cjs.Matrix2D(1,0,0,1,-711.4,-98)).s().p("AkxPUIAA+mIJjAAIAAemg");
	this.shape.setTransform(319.3,0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.bf(img.Dave_1, null, new cjs.Matrix2D(1,0,0,1,-663.7,-98)).s().p("AgxPUIAA+mIBiAAIAAemg");
	this.shape_1.setTransform(283.7,0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.bf(img.Dave_1, null, new cjs.Matrix2D(1,0,0,1,-299.4,-98)).s().p("EguwAPUIAA+mMBdhAAAIAAemg");
	this.shape_2.setTransform(-20.7,0.2);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-320.1,-97.8,670,196);


(lib.Pat = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// eyes
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#642100").s().p("ABaAXQgHgIAAgIIAKgWIABAAIARABIAAAIQAAAJABAEQAEAIAMAEIAPAAQgFANgLAGIgUAAIgRgPgAiLAAQgDgGAAgPQAAgDAEgHIACgEQALgCANAAIAAAJQAAAIADAHQAHAMANAAIAGgCQgHAQgUAAQgVAAgIgNg");
	this.shape.setTransform(25.9,-124.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACZAiIABgBIACgEQAEgLAAgNIAKAIIAEAEQgEAFgMAMgABEADIgEgFIADAAIADgCIAHgDIADgBIAAAAQgDAIgBAFIgBAFIAAACQgEgCgDgHgAB6gBQAAgDADgEIAAAAQAMADAKAFIAAALIgQABQgJgLAAgCgAhLAIIADgGQAEgIAAgMIgBgHIAMAHIAPALIADAEIgHAEQgHAEgOADgAihgGIgMgKIAEgBIAKgHIAIgDIAAAKIACAPIABADIgNgHgAhlgaQAAgCAEgFIAPADQAEAFAAAIIAAACIgEADQgCACgEAAQgNAAAAgQg");
	this.shape_1.setTransform(25.7,-125.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#993300").s().p("AAXALIAAgDQABgEAJgFIALgJQA7ADAJAFIAMAJIgGAAQgWgGgIAAQgYAAgQAFQgRAGgEAAQgBAAAAAAQgBAAgBAAQAAgBgBAAQAAAAAAAAgAhhAEIgPAAIgGgDIgGgBQAEgDAJgFIAGgDIAEAEIADAEQABAAABABQAAAAAAABQABAAAAABQAAAAAAAAQAAAEgBAAIgBAAg");
	this.shape_2.setTransform(32.2,-137.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AA7A9IAAgCIACgGQAAgGAEgIIAAgBIgDACIgHADIgDABIgDAAIgCAAIgBgBIgBgBIAAgEQgBgNAjgKQAjgKAVAOQAQANANAeQgCAEgCABIgCgBIgDgEIgKgIQAAANgFALIgCAEIAAABQgKATgaAAQgpAAgCgpgABGA7QgBAJAHAHIARAQIAUgBQAMgGAEgMIgOAAQgNgFgDgIQgCgEAAgLIABgIIgRgBIgCAAIgJAYgABrAuQAAAEAJALIAQgBIAAgNQgLgGgLgCIAAAAQgDADAAAEgAijA2IgBgEIAAgGIgCgOIgBgKIgIADIgJAGIgEACIgKAGQgEgCgCgCQATgnA8ABQA9AAASAvQgCAEgDABIgDgDIgEgEIgOgLIgMgHIAAAHQAAAMgDAKIgDAFIgBACQgKATgWAAQgfAAgJgXgAiWAPIgCAEQgEAIAAACQAAAPAEAHQAHAOAWAAQATAAAIgRIgHABQgNAAgHgMQgDgHAAgIIABgJQgNAAgMACgAh0AUQAAARAMAAQAEAAADgCIADgDIAAgCQAAgIgDgFIgPgDQgEAFAAABgACLhCQgSAAgXAGIgUAGQgNAAgDgHIAAgKQAAgiA4AFQA4AFAfAuIgDADQgBACgEAAQgogWgSAAgABShQQgJAHgBAEIAAADQAAAAAAAAQABAAAAABQABAAABAAQAAAAABAAQAEAAARgGQAQgFAYAAQAIAAAWAGIAGAAIgMgLQgJgFg7gDIgLAJgAhCg9IgLgHQgHgGgCgFIAAgBQABgBAEAAIAGACIAGADIAGADIAPAAQACABAAgGQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBgBAAIgDgEIgEgEIAAgFQAOgCADAHQADADAAAJIAAAKQgDAFgHACg");
	this.shape_3.setTransform(27.3,-130);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#993300").s().p("AA/AIQgBgFAHgDQAyABAPAEQAIADAEAEIhBAFQgSAAAAgJgAhfACIgygKQARgJAVACQAYACAFAPg");
	this.shape_4.setTransform(28.7,-132.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("ABEA2QgRgMgFgHQgGgFgCgFIAFABIAAgDQABgBAJAHIACABIASANQAcAQA2gHIABAAIABAAIABAAQAEABABAEQgFAIgDABIgCABIgFACQgNAFgQAAQgWAAgdgUgAigAoIgLgFQgSgEgGgHQACgCAGAAIAAgBIAAgBQAAAAABAAQAAAAABgBQAAAAABAAQABAAABAAIAMAFQAWAEAZAAQAcAAANgEIALgFIAFABIAEgDIADAAQABAAAAABQAAAAAAABQABAAAAABQAAABAAABQAAAHgSAKQgTAKgUAAQgUAAgagJgABJgUQgFgCAAgNQAAgdBAAOQBAANAAAQIAAAEIgCACIg0ABQg5AAgMgGgABOgiQAAAJATAAIBBgFQgEgEgIgDQgPgEgzgDQgGAFAAAFgAhNgdQgGgCgYgEIgngGQgBAAAAgGQAAgeAvAEQAwAEAAAcQAAAIgFAEgAiCg0IAzAMIARAAQgFgRgYgCIgIgBQgQAAgPAIg");
	this.shape_5.setTransform(27.1,-128.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABiAFIgCgFIASAGIAKAFIgBAAQgEAEgSAAIgDgKgAh0AAIAAgCIgHgMIASADQgFAFgCAGg");
	this.shape_6.setTransform(28,-124.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#642100").s().p("ABcADIAAAAIACgBQAOgCAMgBIAAABIAEALIADAFQgagBgJgMgAhqAAQgTgEgBgJIAAgBIATgBIAGAAQAAAEACAGIAEAFg");
	this.shape_7.setTransform(24.5,-124.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#993300").s().p("AB8AMQgjgIgdgBIgCgCQgBgBgBgCQAAgVAvANQAuAKAGASIgfgGgAiagFQASgMARAAQAUAAAGAOg");
	this.shape_8.setTransform(30.3,-133.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AA6BMIgGgGIAAgGQAEAAAIAFIANAHIgCAEIgFABQgHAAgFgFgAA/A6IgHgHQgJACgFAAQgBAAgBAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQABAAAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAIADgEIgBgBIAEgIQAEgEAXgBQARAAANABQAVABAPAEIgHgMQABgEABgBIAEAAQACAAAHAMIAHALQAJAEAEAIIgBADQgBACgEAAIgJgCIgBADQgBABgEAAIgEgCQgCAFgHADQgKAEgMAAQgdAAgQgPgABqAzIADALQARgBAEgDIABgBIgKgEIgSgHIADAFgABCAwIgBABIAAAAQAIAMAbABIgDgFIgFgNIAAgBQgLABgPAEgAiHBDQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAgFAKgCIgHAAQgQABgJgMQgEgHgBgHQgHABgFACQgKAHgGACQgEgBgBgCQAEgIAGgFQABgDADgBIACgBQAKgGARgBIALAAIABgBQAkABAPAHIADACQAQAHAPALIgBAEQgBACgEAAIgPgGIgBABIgJgFQgCADgEAFIgGAHIABAAIABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAABQAAABAAABQAAABAAAAQgBABAAAAQAAAAAAAAIgEABQgYACgGADIgEgBgAhsAqIgBACIAEAAQACgGAGgFIgSgDIAHAMgAiZAeIAAABQABAJATAEIAKAAIgDgFQgDgGAAgEIgFAAIgTABgABXggQgIgDgCgFIAAgJQAAgjA8AQQA8AQAAAYQAAAGgDAJQABADgHAAQg7gSgqgEgABXgyQAAADACACIACACQAdABAjAIIAeAGQgGgSgtgMQgSgFgLAAQgSAAAAANgAhWgoQgEgBgpgBIgEgCQgBgBAAgEQAAgIANgLQANgLAMgBQAAABAXAHQAYAIAAALQAAAGgIAHgAh7g1IA9ACQgHgOgTAAQgSAAgRAMg");
	this.shape_9.setTransform(27.3,-129.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#642100").s().p("ABVATQgGgJAAgKIAAAAIAFgEQAJgGAQgCIAAADIACAKQAGAMAWAAIABAAIAAACIgBADIAAABIgDAFIgEAEQgHAGgMAAQgTAAgJgPgAiIAAQgDgDAAgIIAAgBIAAgJIAAgEQALgGALgCIAAAHQAAAHADAEQAFAKAQAAQAGAAAFgCIACAAIABgCQAAAGgDAEQgGALgRgBQgXAAgIgLg");
	this.shape_10.setTransform(24.3,-126.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("ACQAdQADgHABgKIAAgFIAAAAIAAgEIACgCIABgBIADABIAFAEIAEAFIACADIgFAGIgGAFQgFAFgFADIAAgDgAhMAOQACgEABgGIABgEIAAgDQAAgLgEgHIgBgCIABgCQALAEAMAGIAIAFIAFAEIAFADQgFADgIADIgUALgAB2ABQgCgBAAgIIAAgCIALAAIAHABIABAIIACAGIgFAAQgLAAgDgEgAihgBIgDgFIAMgJIAAASIAAABQgFgBgEgEgAghgMIADADIAAABIgDgEgAhYgLIgRgCQgFgHAAgEQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAABAAQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAAAgBIABAAIAJABIACAGIAFAEIACAFIABACIgBACIgCAAg");
	this.shape_11.setTransform(24.7,-126.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AA6BMQgFgIgCgIIgBAAQgDgBgCgCQAHgqAqACQALgCAIAFQAHABAHAFIACACIABABQAHADAIAIQAUATAAAKQAAAIgHABIgNgKIAFgHIgDgDIgEgEIgEgEIgEgEIgBADIgBADIAAADIAAABIAAAEQgBAKgDAIIgBACQgIASgYAAQgaAAgMgWgABBAuIgFAFIAAACQAAAJAGAKQAKAOATAAQAMAAAHgFIAEgFIACgEIABgBIAAgEIABgCIgCAAQgWAAgGgLIgCgMIAAgEQgPACgKAGgABkAlIAAABQAAAJACADQAFAEAPgBIgCgIIgCgIIgGgBIgMABgAhsBVQAAgBAAgBQAAgBAAAAQABgBAAAAQAAgBAAAAIAEAAIAZgDQAKgBAFAEQgEAEgXAGIgQAAIAAAAQgCAAAAgFgAicBAQgKgHgBgFIgBAAIAAgUIgLAIIgNAJQgFgGAAgCQAAgBALgNQALgNAEgCQAHgDAJgGQAMgDAjgCQAkAEAOAPIAKASIADADIADAHQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAIgGgFIgEgDIgGgEIgIgEQgLgHgLgEIgDgBIACADIABACQADAIAAALIAAAEIAAAFQgBAGgCAEIgBABQgIALgYAAQgSAAgOgLgAidAZIAAAEIgBAJIAAABQABAIADAFQAHAMAYAAQARAAAGgLQADgFgBgGIAAACIgCAAQgFABgHAAQgPAAgGgJQgCgFAAgHIAAgHQgLADgLAFgAh7ASQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABQAAAFAFAHIARABIACABIACAAIgBgDIgBgCIgDgFIgEgEIgCgGIgJAAIgBAAQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAgACtglQgRgNgGAAQgxgIgJgEQgEgDAAgLQAAggA3ARQA3ARAAAgIgBAPQABACgHAAQgCAAgQgMgABqhVIgIAJQAAAEABABIACACQAqADAPAHIAVAKQACgBAAgHQAAgEgdgNQgagMgPAAIgFABgAhNg1IAPgLIAQAAQAHgCAEgLQAAgFgCgEIAHgGQAFAFAAAKQAAALgFAFQgIAIgVAAIgSAAg");
	this.shape_12.setTransform(26.2,-131.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#993300").s().p("ABjAIQgPgIgqAAIgCgCQgBgCgBgDIAJgJQAPgDAfAOQAdALAAAEQAAAHgCABIgVgKgAh5ACIAQgLIAJgIQABADAAAGQgEAJgGABg");
	this.shape_13.setTransform(32.1,-138.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4}]},2).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},2).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10}]},2).to({state:[{t:this.shape_5},{t:this.shape_4}]},34).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},2).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},2).wait(76));

	// body
	this.instance = new lib.PatBitmapped();
	this.instance.setTransform(-55.7,-165.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(120));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.7,-165.7,137,211);


(lib.Jose = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Eyes
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#914706").s().p("ACCAkIgDgbQAAgLAHgJQAEgEACgJIATAEQgEAJAAAEQAAAHAFAHQAJAKAMAAQAMAAAGgLIAEgIIADACIAEAFIgHAVQgKAjgcAAQgcAAgHgZgAjHgDQgJgNgBgKQAAgEAHgTIACgJQAMgCAKAAQgDAIAAAJIAAAKQACAEAGADIAUAAQAOgEAFgQIAHAFQglAYgaAaQgBgFgIgHg");
	this.shape.setTransform(-462.6,-465.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3E1E00").s().p("ABJAkQgNgVAAgQQAAgJAEgMQAEgNAGgFIAMALIAPAPIAIAFQAGADAKACIAlABQAdACANAFQARAJAKASQAHAPACAQIgZgCQgYAAgRAGQgQAFgRAAQguAAgWgjgAipgDQgYgMguALQAFgYAHgLQAQgZAiAAQAUAAAGAEQAHAEAWAAQAdAAAQgGQAMgHAFgBQACAHAAAPQAAAWgGAMQgNAZgnAAQgXAAgegOg");
	this.shape_1.setTransform(-462.5,-480.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABKgkQAAgFAPgGQAFAGAPADIADABIARADIAAABIAAAjQAAAaAGANQADAIAFAGIgEgBIgLgBIgEABQgBAAAAABQAAAAAAABQgBAAAAABQAAABAAABQAAAEACABIABABIAAAAIACABQgagEgbhigADmAaIAEgJIABgDIAAgBIAAAAIACgBIAAAIIgIANIABgHgAjGAJIgOgCIgBAAIAAgBIgBABQgHgHgHgOQgIgUAAgRIABgKIABAAQAAABAAAAQAAAAAAABQAAAAABABQAAAAABABQADACADAAIAEAAIAAgBIATgEIAFgBQgIASAAAMQAAAMAFALQAGAIALAKIgOgBgAC4gOIACgKIAOADIAGACIAAADQgCAPgKAAQgKAAAAgNgAiYguIgBgBIAAgEQAAgCADgIIACgEQAKACAGADIgGAOg");
	this.shape_2.setTransform(-464.1,-465);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CD9967").s().p("AhxAjQgOhjBugIIADAAQAaADATAPIAAgBIADADQApgGAgAQQgqARghAUIAAgEQAAgXgugHQgtgHgYAaIgPAHIgBABIgBAAIgBAKQAAAPAJAUQAGAPAHAIIgEAEQAAAFAFACQAEADAIABIgLACQgggKgEgcgAAcAEQAkgYApgUIADgCIAIAFQgaAlgkAaQgfAVgoAQIgRADQAZggAlgeg");
	this.shape_3.setTransform(-477.7,-469.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0C1D00").s().p("ACdCcQgMgDgmgCIgDgBIgBAAIAAgBQgCgBAAgEQAAgBAAgBQAAAAAAgBQABgBAAAAQAAAAABgBIAEgBIALABIAEABQgGgGgDgIQgFgNAAgaIAAglIAAgBIgRgDIgEgBQgPgDgEgGQgCgDAAgDQAAgFAOgFQARgGAZADQA9AJAXAVQAPAOAAAZQAAAFgFAGIgCABIgBAAIAAABIgBADIgDAJIgCAHIgBAEQgKAVgRAHQAEACAAAEQAAAFgCABIgEABIgUgHgACABCQgHAJAAANIACAbQAIAZAcAAQAcAAAKgjIAGgVIgDgFIgDgEIgEAKQgGALgNAAQgMAAgIgKQgGgIAAgIQAAgEAFgJIgTgEQgCAJgEAEgACjBFQAAANAKAAQAKAAACgPIAAgDIgGgCIgOgDIgCAKgAjrBnQgEgCgBgFIAFgEIABgBIAAABIABAAIAOACIAOABQgMgLgFgJQgFgLAAgMQAAgMAIgSIgFABIgTAEIgBABIgDAAQgDAAgDgCQgBgBgBAAQAAgBAAAAQgBAAAAgBQAAAAABgBIAAgBIAPgHQAZgYAtAHQAwAFAAAXIgBAEQAigUAqgPIABAAIgEACQgpASgjAaQgoAegZAgIgfAFQgJgBgEgDgAjOATIgDAJQgGATAAAEQAAAKAKANQAIAJABAFQAagcAlgYIgHgFQgFAQgOAEIgUAAQgGgDgCgEIAAgKQAAgJADgIQgKAAgMACgAirAWQgEAIAAACIAAAEIABABIAPAAIAGgOQgGgDgKgCIgCAEgAA9gaQgSgaAAgXIABgaQADgNAPgNQAMgHAOAPQATAWAMAFQAlABAXADQAqAFARAjQAHAPAHATIAGAPIAAAFIgCABIgHABQgCAAgIgEQgIgEgUAAQgUAAgRAFQgQAGgWAAQgxAAgaglgAA8hgQgEAMAAAJQAAASANAVQAWAjAtAAQARAAARgFQARgGAYAAIAZACQgCgQgIgPQgKgSgRgJQgMgHgegCIgkgBQgLgCgFgDIgIgFIgQgPIgMgLQgFAFgEANgAi9hEIgZAAIgCABQgJAAgMACIgMACQgDgBgCgDQgDgEAAgHQAAgQANgXQAVgjAnAAQAWAAAIAEQAJAFAUAAQAeAAAkgSQAHgEABAGIABAEIACgBIACAKIgEABIAAATQAAAegFANQgPAkgyAAQgoAAgdgVgAiuhNQAeAQAYAAQAnAAANgbQAGgMAAgWQAAgPgDgHQgEABgMAHQgRAGgcAAQgXAAgGgEQgHgEgUAAQgiAAgQAZQgHALgFAYQAWgFARAAQATAAAMAGg");
	this.shape_4.setTransform(-462,-473.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#3E1E00").s().p("AA/gUQAAgGADgLQBxAIAzAOQAYAGAJAKQAGAOAHAGQghgFgtATQgyAVgSAAQhDAAAAhMgAjVARQg1gLgJACIAAgCQAcg7AfgCQAJAAAbAEQAdAGAYAAQAbAAACgGIABABIAAALQAAAXgGAQQgMAcgmAAQgGAAg2gLg");
	this.shape_5.setTransform(-463.3,-472.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("ACTByQgVgEgIgGQARggArAmIgBAEQgBADgEAAQgIAAgRgDgAC5BTQgsgJhGAAIgKgCIAAgGQAAgFAIgFQAMgHAQABIAAgBIBEAAQAdAIAOAIQAMAHAIAMIgBAGQAAACgGAAQgNgFgXgEgAjtBBQgEgCgBgEQAGgMARAFQAMACAKAIIgDAFQgCACgEAAQgXAAgIgEgAjAAkQgKgEg8AAQgJAAgEgHQAEgEgBgEQAGgDAwgEQAWgEARAHQAOAFAAAFQAAAEgCAGQgDAGgDAAQgKAAgJgDgAA3gNQgKgZABgdQAAgUACgEQACgEAMAEQA4APA2AAQA8AAAjAfQAYAWAAATIgBAEQgCACgGAAQgFAAgPgCQgPgDgHAAQgXAAglASQglATgPAAQg2AAgTgvgAA9g4QAABMBDAAQASAAAxgUQAugSAgAFQgGgGgGgOQgJgMgZgGQgzgOhwgIQgDALAAAGgAjMgBQgXgLgKgBQgqgCgGgCQgFgCAAgKQAAgTARgXQAWghAnAAQAoAAAaAIIAfAAQAVgaAFAIQACACAAAVQAABihEAAQgcAAgVgIgAjYgRQA3ALAGAAQAmAAALgeQAGgQAAgXIAAgLIgBgBQgCAGgbAAQgXAAgdgGQgcgEgJAAQgeACgcA9IAAACIADAAQAMAAAuAJg");
	this.shape_6.setTransform(-463,-469);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ADdAoQADgKACgIIAFAAIAJAAQAAAIgQAMIgGADIADgFgABSAUIgFgUIAAAAIACAAIAVAAIgBALQABAMACALIACAHIgFABQgKAAgHgWgADUAaIAAgBQAAgHgBACIgEABIgBgBQgJACgSABIgJgTQAZACAJAFIAJAHIAAAIIgBABgAjYgGQgEAAgKgOQgIgOgBgCIAAgCIAFAAQACgBAIgDIAHgCIAFAPIAEAIIAAABIAAADQgGABgEADQAAAEADADgAiggtIAcABIgGAGIgGAGIgQgNg");
	this.shape_7.setTransform(-464.4,-464.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#914706").s().p("AC2AtQgOgGgVgDQgWgCgJAEIgEgIQgFgLAAgJQAAgDACgFIACgCQAbAAATABIAAAHQAAALABACQACAJALAFIAWAAIAHgFQAEgDAAgDQAAgBAAgBQAAgBAAgBQAAAAAAAAQgBgBAAAAIgBAAIAEgBQABgBAAAHIAAABIAAABIAAAAIgPASIgDAEIgHgDgAisgPQgPgDgIgBIgEgBQgCgOgDgIIgCgEIAOgBIAHABIAEAEQABAFADAFQAGALANADIAAAAIgBACIgBgBQgGgCgEADIgCACIAAgBg");
	this.shape_8.setTransform(-463.9,-464.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#3E1E00").s().p("ABQAhQgKgTAAgRIACgiQAGAAASAMQAaANAsAAQBGAAARAVQAHAIABANIABATQgTgCgxAIQg2AJgNAAQggAAgPgfgAi0AEQgngOgNAAQgJAAgUAEIAPgdQAMgTARgEQAUgLAqAMQA1APAFAAQAXAAARgOIABABIAAAEQAAAMgQAZQgXAhgiAAQgOAAglgPg");
	this.shape_9.setTransform(-463.1,-476.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AC5CDIgEABQgFAAgJgDIgWgHIgTACIgLABIAAAAQgBACgEAAQgMAAgFgQIgCgHQgDgLAAgMIABgLIgWgBIgBAAIgFgBIgCgCIAAAAIgBgEQAAgDAOgHQAOgFAOgCQBLABAfAOQAIADAWAVIgBAGIgHACIgIAAIgFAAQgCAIgDAKIgDAFQgIARgLAAIgDgBgACNBsQAVADAOAGIAHADIADgFIAPgSIAAAAIAAgBIAAgIIgJgHQgJgFgYgCIAJATQASgBAJgCIABABIABAAQAAAAABAAQAAAAAAABQAAAAAAABQAAABAAABQAAAEgEADIgHAFIgWAAQgLgGgCgIQgBgDAAgLIAAgGQgTgCgbgBIgCAEQgCAFAAADQAAAIAFAMIAEAIQAGgDAKAAIAPABgAjfBBIgEgDQgDgDAAgEQAFgDAFgBIADgBIgDgDIgDgIIgGgPIgHACQgHADgDABIgEAAIgCgBIgCgDIAAABIgBgFQAAgcBBAFQA4AEAIAMIADAAQABAAAAAGQAAAHgOALIgJAHIgDADQgCADgDAAIgBAAIgEADIgFgDIgBgBIAAAAQgNgDgGgKQgDgFgBgFIAAgFIgEAAIgHgBIgOABIACAFQADAHACAOIAEABQAIABAPAEIAAABIACgCQAEgEAGACIABACIAAAEIgBAHIgGACIgGgCIAAACQgCACgGAAQgVgEgQAAgAicAkIAHgGIAGgGIgcgBIAPANgAA/gSQgHgZACgaIgBgcQABgGAIACQBdAVAcAEQAtgEAaAmQAUAbAAAWIAAAIQgCAFgFAAIgLgFQgLgFgSAAQgMAAgmAKQgmAKgMAAQg0AAgQgwgABHg0QAAATAKAUQAPAcAhAAQANAAA1gJQAygGASAAIgBgQQgBgNgGgJQgSgXhGAAQgsAAgagNQgSgMgGAAIgCAigAi0geQgogQgMAAQgVABgJAIQgFAKgEABQgFgCgBgDIAAgGQAAgNANgaQAPgbANgJQAhgVArALIA+ARQAVAAAPgNIAPgNIAGABIABAIQAAAcgNAdQgXA0gzAAQgOgBgngQgAizgrQAmAPANAAQAjAAAWgjQAQgYAAgNIAAgEIgBAAQgRANgXAAQgFAAg1gOQgqgNgUALQgRAEgMATIgPAdQAUgDAJAAQANAAAnAPg");
	this.shape_10.setTransform(-463.3,-471.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_6},{t:this.shape_5}]},53).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7}]},2).to({state:[{t:this.shape_4},{t:this.shape_1},{t:this.shape_2},{t:this.shape},{t:this.shape_3}]},2).wait(1));

	// body
	this.instance = new lib.JoseBitmapped();
	this.instance.setTransform(-541.6,-492.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(58));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-541.6,-492.6,165,212);


(lib.dave = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Mouth
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag/AZQgWgDgEgBIAGgBQArgIAsgQQArgRAqgHIgCABQhVA4gkAAQgGAAgXgEg");
	this.shape.setTransform(3.3,-117);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AhaBPIgtgNQAAAXgHADQgFgHAAgFIAAgKQAAgVAHgFQAFAGAAAFIADgBIAFAEQAEAEAnAAQA6ABAzgYQAvgWAugEQgJgNgDgIIACgEQAMAKAPAPQARAWABALQgCAEgDABQgLgLgLgQQgUAUgfATQgzAfgnAAQgUAAg3gPgAAcAwQgtASgrAIIgFABQAEABAWADQAXAEAGAAQAjAABWg6IACgBQgqAHgrARgAiXAAQAAAAgBAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAgFAEgLQAEgMAEgCIAEABQAAAAAAAAQABAAAAABQAAAAAAABQAAABAAABQgIAbgEACIgEAAgAADg5QgogVAAgLIAAgEQAEAAAPALQAQANAKADIApAMQAYAIAKAGIAAAEQgBABAAAAQAAAAgBABQAAAAgBAAQgBAAgBAAQgeAAgtgXg");
	this.shape_1.setTransform(0.9,-122.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAAgCQASgIAbgIIgDADQgLAMgKAFQgSAMgvAFIAsgVg");
	this.shape_2.setTransform(9,-118.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("Ah9BXIgBgJIABgMQABgGAIgHIAEAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABIgBALIABAAQAOADAEgCIABABIABAAQA7AAA+gbQA8gaAdgHQgJgIAAgIIAAgBIgDgGIAAgFQAIgBAOAOQAJAHARAVIgBAEQAAABAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAIgEAAIgBAAIgDgCIgHgFIgDgCQgFASgfAOQg0AWhrAAIgMADIgLACIgHAAIgBABQgEACgDAAIgKgDIgDgBIgDAOIgEACQgEgDAAgFgABIAlIgtAWQAxgFASgMQAKgHALgMIACgDQgaAIgTAJgAiZgMQgBgHABgHQACgNAJAAIABAMIgCAWIgFACQgFgCAAgHgAgMhCQgmgMACgQQAFgBAjAOQApARAnAGIAEADIABADIgBAGIgEABQhGgQgOgFg");
	this.shape_3.setTransform(1.7,-122.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AhsBNIABgEQABgGACgCQAEACACADIAAACIAPgCIgBgCQACgCAOADIAxgFQAPgDAcgJIAFgCQAmgOAhgVIABABIAYgOIgQgKIAAgDIADgEQAHACATANQAVAMADAHQgDAFgCABIgZgTQgGAMgjAOQgPAIgdANQg+AbgzAAIggAAIAAAHIgGADQgEgGAAgHgAihgOQAAgRAIgCIADABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAABIgCAYIgFAEQgFgHAAgHgAAngyQgtgHgVgEQgngIAAgQIAAgEIAmAOQArAOAxABQAEABACAEIgDAFg");
	this.shape_4.setTransform(3.5,-123.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape}]},21).to({state:[{t:this.shape_3},{t:this.shape_2}]},4).to({state:[{t:this.shape_4}]},2).to({state:[{t:this.shape_4}]},75).to({state:[{t:this.shape_3},{t:this.shape_2}]},4).to({state:[{t:this.shape_1},{t:this.shape}]},2).wait(12));

	// Eyes
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#999900").s().p("AhtAPQAFgBADgBQADgDgBgJQACgCAGgBIABACIABAIIAAAFIgLABIgJACIAAgBgABhgPIACAAIAAADIAAAKQACAFAJACQgMgCgNADQAAgOAMgHg");
	this.shape_5.setTransform(-5.2,-144.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AiSAdIgBgBIAAgJIAIgMIACABIABgFIAAAAQAQgQAVAAQAQAAAGAEIAFAEQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAIADABIgCADQgBABgFAAIgFAAIAAgBIgFgDIgFgCQgRgKgNAJQgMAFAAAOIABAGIgBAAIAAABQgHACgEAEIgDAAgAB0ATQACgMAAgFIADgBIgHgDQgIgKgKgHIgIgBIgKABQgGABgFAEIgGAAIAAAEIgBABQgHAIAAAKIAAABIAAAAIABADQgLACgCABIABAGQgQgGgFgEIgBgEIACgBIgCgDIgBgIIAOgLQAVgNAWAAIACAAIAEABIACAAQANADASAOIANAKIgBAAIACAAIAKAGQAEAAACgCIABgCIAAgBQACABAAADQAAAGgHAIQgGAGgFABIgOgHgAhgANQgEgCAAgEIABgFQADAAAGADIAEADIgHAHIgDgCgABYAAIgBgIIAIAAQAGADADADIgHACIgGAAIgDAAgAhVgVIAKACIAIAHIAAAAQgJgGgJgDg");
	this.shape_6.setTransform(-3.1,-144.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AibBTQgIgHgBgFQAFgBAMAGQALAFAFAFIgBADQgCACgDAAQgJAAgJgIgAAsBJQgDgBgBgCQAAgFAEgCIAcAAIAKAHIgBAEQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAQgEgCgdgBgAijA5QAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAgBAAIAEgEQAFgEAHgCIACAAIAJgCIALgBIAEAAIgEgFIAAgKIAAgDIgCABQgGABgCAEQABAJgDADQgDABgFAAIgBAAIAAAAIgBgFQAAgOAMgIQAMgIASAKIAFADIAFAEIAAABIgBADQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgBgBIgFgDQgFgEgDAAIgBAGQAAADAEADIADACIAIAEQgCAFgHAAIgGgBIAAABIgCAGIgTAEIgVACQgBAAgBAAQgBAAgBAAQAAAAgBAAQAAAAAAgBgABZAyQgLgEgwAAIAAAAIgEAAIAAgCIgCgGQACgBAMgCIgBgEIAAAAQAAgMAHgIIAAgBQADgDAEgCQAEgDAHgBIAKgBIAHABQALAHAIAKIABACIAAAVIAPAHIAAAAQgBAFgIAAQgEAAgMgDgABVAjIACgCIACgCQgFACgHAAIgBAAIAJACgAAwAiQANgCAMABQgJgBgCgIIAAgJIAAgDIgCAAQgMAHAAAPgABIAVQAFAAAEgBIAGgCQgCgDgHgDIgHAAIABAJgACPArIgJgLIAAgFIABAAQADgFAKgFQAMgFAPAAIABgBQAAABAAAAQABAAAAABQAAAAAAABQAAABAAABQAAAEgLADQgOADgJADIAJAFIAPAJIgBADQgBACgFAAQgLAAgGgFgAiqAqQAAAAAAgBQgBAAAAAAQAAgBAAgBQAAgBAAgBQAAgUAbgOQAUgJAXAGQAJACAJAGIAEADIgBADQgBACgEAAIgEgBIgEgEQgHgEgPAAQgVAAgQARIAAABIgDAEIgJALIgCADIgEgBgAgEAbQgHgKAAgRIACgCQADgEADgBIADACIABABIAAACQAQgKAnAAQBCACAIAhIAAAAIgBADQgCACgEAAIgKgHIgBgBIgOgKQgRgMgNgDIgGgBIgCAAQgWAAgWALIgNAKIABAKIAAAFIABAEIAAACIgFACQgDgFgBgGgAipAHQADgGAKgGIgPAAQgFgCAAgFQABgCAmgDQAggEABgOQAAgEgFgBQgHgCgDgEIAAgFQANgCAHAGQAFAFABAIQAAAJgIAGQAFABAFADQgBADgEACIgOAAIAAgDQgLAFgRADIgCAAIgJAGIgPAKQgDgCgCgCgAAPgMQgBgBABgEQgBgGAEgCQAMgEAqgBQADACACADIgCAFQgwAAgEAEQAEAFgHABIgFgCgAB4gqQgEgFgYAAQgHABgfACQgTAEgFAAQgcAAgMgUIgJgUIABgIQACgEAGADIAGAUQAJASAZAAIBEgGQATAAAIAHQAGAEADAGQgEAHgDABQgBgBgGgJg");
	this.shape_7.setTransform(-1.5,-147.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#999900").s().p("AAPAJQgNgCgGABQgCgDgFgFIgFgFIAQgDIALAAIgBABIgBAEQAAADAHAIIABABIgCAAg");
	this.shape_8.setTransform(4.6,-144);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ACFAQIgMgFIAAgFIABgEIAAgBQAFgEAFAAIABAAQAIADAFAGQgCAEgEADIgHADgAAYADIAAgEIAAgEIATgGIAAABIAKAMIgBACIAAAAIgBAAIAAABQgFACgOACQgHAAgBgGgABjgBQgLgEAAgGIABgDIAAgBQAPABALADQgEABgBAEIgCAFIgCABIgHgBgAiRgCIADABIAHgEIADAFIgHAAIgGgCgAhsgHIgBgCQAMAAAJgEQAEABAAADIgCAFIgTACIgDgFg");
	this.shape_9.setTransform(-2.4,-143.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AieBMIgBgCQgCgBAAgEIABgEIAAAAIARAAIABAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAADgEACQgDACgDAAgABBBLQgEgCgRgBQgCABAAgGQAAgEAHgBQAOgBA2AEQADABACAEIgCAFgABNA1QgkgGgJAFQgDgBgCgCQACgEAFgDIABAAIABAAIAAAAIACgBIgBgBIgKgOIAAgBIgTAGIgDABQAAAJAFALQgDAEgDABQgFgIgCgHIgBgIIgCgDQAAgFADgEQABgOAGgGIAEABQAAAAABAAQAAAAAAABQAAABAAAAQABABAAABIgBAGQAQgFAhADQAzAGATAQQAKgGAdgMQADABACAEQgHAFgRAIIgMAGQAHAAAQAEQAYAFABAEIgCAEIgFABQgLAAgPgEQgKgDgFgDQgBAAAAABQgBAAAAABQgBAAAAAAQAAABgBAAIgDgGQgFgGgHgFIgBAAIgGgEIAAABIgDAHIgBACIgBABIgBAEIgBACIgBACIACABIANAFIAAAAIAAAEQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQgRgEgSgDgABEAnIADABIgCgCQgHgIAAgFIABgDIABgCIgNAAIgQADIAFAGQAFAGACAEIAHgBIAOABgABJAWIgBADQAAAGALAEIAHADIACgDIABgFQABgEAFgBQgMgDgOgBIAAABgAi1A2QABgIAIgEIgDgBQgIgGgBgBIAAgGQAKAAAHADIAEACQAAAAAAgBQAAAAAAAAQAAgBAAgBQgBAAAAgBQAAgJAVgGQAWgGAXAMIgGADQgKAEgLAAIABACIACAFIABAEIAAAEIgBABIgEACIgDgBIAIAGIgCAEIgGABQgGgCgZgBIgDACQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAgBAAQgDAAgDADQgBACgDAAQgEgBgBgCgAicAmIAHgBIgCgGIgHAEIgDgBIAFAEgABMAAQgLgDg3ABIABgBIgDAAQgIAAgEgGIAAgGQAOAAAHAHQALgHAXACQAaACAQAKIABABIAAADQAAAAgBABQAAAAgBAAQAAAAgBABQgBAAAAAAQgDAAgLgFgAirAAQAJgSAZgCIAggCQAEgCgBgMQAAgLAGgBQAEADAAAEIABAJQAAAWgeAHQgjADgKACQgEgBgBgBgAgQguIgHgUIAAgIQACgEAHADIACAUQAKASAiAAIBGgGQAbAAAKAKQgFAFgHgCQgRgCgJAAIhFAGQgiAAgOgUg");
	this.shape_10.setTransform(-0.7,-147);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAjA2IgQgMIAAgFIASAGQAUAJA5AAQAUAAADgDQABgCABgGIAGAAIABAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAFgJAGQgJAGgOAAQg5AAgXgJgAieAuIgBgFIAAgEQAEAAAEACQAGAEAGADQgBAFgIAAQgIAAgCgFgAgGAZIAAgSQADgIAHgJIAEABQAAAAABAAQAAABAAAAQAAABAAAAQAAABABABIgEAQIAQgDIBBAAIAnAGQAMAAAKgFIATgJQADAAACADQgFAJgTAIQgPAGgGAAIglgHIhGAAQgDACgOAAQgCALACAKQgBADgCABQgGgHAAgOgACTAcIAAgDQAAgHALAEIAdAPQgCAFgDABIgjgPgAihAcIgEgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAgBIAAAAIAAgBQABgGAHgIQAJgHADAAIAEAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAABAAABQAAAEgGAIIgDAEIAbgDQAEAAAFAHQAAADgEACgAi5gGIgBgCQAEgDACgGQAMgFA/gCQAHgCAAgGQAAgJACgBQAKAEAAAFQAAANgOAGQgWAJg6AAQgBAAgBAAQgBAAAAAAQgBAAAAAAQAAAAgBgBgAgJgkQgJgIAAgLQAAgHAEAAQADABAGANQAGAMAVAAQAHAAAigJQAigKAKAAQAWAAAJAFQAGADABACQgGAEgFgBQgOgCgNAAQgNAAggAKQggAJgEAAQgZAAgKgLg");
	this.shape_11.setTransform(-1,-145.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5}]}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]},21).to({state:[{t:this.shape_11}]},2).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]},2).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5}]},2).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]},75).to({state:[{t:this.shape_11}]},2).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]},2).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5}]},2).wait(12));

	// Body
	this.instance = new lib.DaveBitmapped();
	this.instance.setTransform(-54.7,-181.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(120));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-54.7,-181.7,123,205);


// stage content:
(lib.productknowledge = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{patIntro:1,patQuestion1:20,patQuestion2:26,"patQuestion2":32,joseIntro:38,joseQuestion1:56,joseQuestion2:62,joseQuestion3:68,daveIntro:74,daveQuestion1:92,daveQuestion2:98,daveQuestion3:104});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_25 = function() {
		this.stop();
	}
	this.frame_31 = function() {
		this.stop();
	}
	this.frame_37 = function() {
		this.stop();
	}
	this.frame_61 = function() {
		this.stop();
	}
	this.frame_67 = function() {
		this.stop();
	}
	this.frame_73 = function() {
		this.stop();
	}
	this.frame_97 = function() {
		this.stop();
	}
	this.frame_103 = function() {
		this.stop();
	}
	this.frame_109 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(25).call(this.frame_25).wait(6).call(this.frame_31).wait(6).call(this.frame_37).wait(24).call(this.frame_61).wait(6).call(this.frame_67).wait(6).call(this.frame_73).wait(24).call(this.frame_97).wait(6).call(this.frame_103).wait(6).call(this.frame_109).wait(1));

	// Question 1
	this.instance = new lib.PatQuote_1();
	this.instance.setTransform(800.2,292.9,0.897,0.897);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.instance_1 = new lib.JoseQuote_1();
	this.instance_1.setTransform(986.6,251.9,0.837,0.837);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.instance_2 = new lib.DaveQuote_();
	this.instance_2.setTransform(911.7,234,0.776,0.776);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(20).to({_off:false},0).to({scaleX:1,scaleY:1,x:830.2,alpha:1},5).to({_off:true},1).wait(84));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(56).to({_off:false},0).to({scaleX:1,scaleY:1,x:1058.6,alpha:1},5).to({_off:true},1).wait(48));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(92).to({_off:false},0).to({scaleX:1,scaleY:1,x:983.7,alpha:1},5).to({_off:true},1).wait(12));

	// Question 2
	this.instance_3 = new lib.PatQuote_2();
	this.instance_3.setTransform(893.9,279.9,0.912,0.912);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.instance_4 = new lib.JoseQuote2();
	this.instance_4.setTransform(991.2,276.1,0.796,0.796);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.instance_5 = new lib.DaveQuote_2();
	this.instance_5.setTransform(923.6,208.8,0.73,0.73);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(26).to({_off:false},0).to({scaleX:1,scaleY:1,x:929.9,alpha:1},5).to({_off:true},1).wait(78));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(62).to({_off:false},0).to({scaleX:1,scaleY:1,x:1039.2,alpha:1},5).to({_off:true},1).wait(42));
	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(98).to({_off:false},0).to({scaleX:1,scaleY:1,x:1005.6,alpha:1},5).to({_off:true},1).wait(6));

	// Question 3
	this.instance_6 = new lib.PatQuote_3();
	this.instance_6.setTransform(886.9,269.3,0.878,0.878);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.instance_7 = new lib.JoseQuote_3();
	this.instance_7.setTransform(996.6,227.9,0.815,0.815);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.instance_8 = new lib.DaveQuote_3();
	this.instance_8.setTransform(937.5,219.8,0.755,0.755);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(32).to({_off:false},0).to({scaleX:1,scaleY:1,x:930.9,alpha:1},5).to({_off:true},1).wait(72));
	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(68).to({_off:false},0).to({scaleX:1,scaleY:1,x:1068.6,alpha:1},5).to({_off:true},1).wait(36));
	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(104).to({_off:false},0).to({scaleX:1,scaleY:1,x:981.5,alpha:1},5).wait(1));

	// Register
	this.instance_9 = new lib.Register();
	this.instance_9.setTransform(887.9,314.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(110));

	// Desk
	this.instance_10 = new lib.Desk();
	this.instance_10.setTransform(-1,768.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(110));

	// Character
	this.instance_11 = new lib.Pat();
	this.instance_11.setTransform(225.7,577.3,1.944,1.944,0,0,0,-1.7,7.8);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.jose = new lib.Jose();
	this.jose.setTransform(744.2,500.3,1.895,1.895,0,0,0,-466.9,-333);
	this.jose.alpha = 0;
	this.jose._off = true;

	this.instance_12 = new lib.dave();
	this.instance_12.setTransform(647.6,544.2,2.086,2.086,0,0,0,-7.7,4.8);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(1).to({_off:false},0).to({regX:-1.8,scaleX:3.17,scaleY:3.17,x:365.3,y:653.1,alpha:1},18,cjs.Ease.get(1)).to({_off:true},19).wait(72));
	this.timeline.addTween(cjs.Tween.get(this.jose).wait(38).to({_off:false},0).to({scaleX:3.03,scaleY:3.03,x:526.1,y:614.2,alpha:1},17,cjs.Ease.get(1)).to({_off:true},19).wait(36));
	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(74).to({_off:false},0).to({scaleX:3.41,scaleY:3.41,x:515.5,y:708.3,alpha:1},17).wait(19));

	// Floor & Ceiling
	this.instance_13 = new lib.Background();

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(110));

	// Off Stage Assets
	this.introCover = new lib.cover();
	this.introCover.setTransform(-1223.3,667,0.432,0.432);

	this.timeline.addTween(cjs.Tween.get(this.introCover).wait(110));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1223.3,667,4261.3,1335.9);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;